import { BrainCircuit, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { askKnowledge, getChatSession, getChatSessions, getCollections, getResources, type ChatDetail, type ChatSession, type KnowledgeCollection, type Resource } from '../api/knowledge'

type Scope = 'THIS_RESOURCE' | 'SELECTED_RESOURCES' | 'COLLECTION' | 'LIBRARY'
export default function KnowledgeAskPage() {
  const [params] = useSearchParams(); const initial = Number(params.get('resource'))
  const [resources,setResources]=useState<Resource[]>([]), [collections,setCollections]=useState<KnowledgeCollection[]>([]), [sessions,setSessions]=useState<ChatSession[]>([])
  const [scope,setScope]=useState<Scope>(initial?'THIS_RESOURCE':'LIBRARY'), [selected,setSelected]=useState<number[]>(initial?[initial]:[]), [collectionId,setCollectionId]=useState<number|undefined>(), [active,setActive]=useState<ChatDetail|null>(null), [question,setQuestion]=useState(''), [loading,setLoading]=useState(false), [error,setError]=useState('')
  const load=()=>Promise.all([getResources(),getCollections(),getChatSessions()]).then(([r,c,s])=>{setResources(r);setCollections(c);setSessions(s)}).catch(()=>setError('KnowledgeOS could not load this workspace.'))
  useEffect(()=>{load()},[])
  const toggle=(id:number)=>setSelected(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id])
  async function open(id:number){ try { const detail=await getChatSession(id); setActive(detail); setScope(detail.scope as Scope); setSelected(detail.resourceIds); setCollectionId(detail.collectionId||undefined); setError('') } catch { setError('This conversation could not be restored.') } }
  async function submit(event:React.FormEvent){ event.preventDefault(); setError(''); if(!question.trim()) return; if((scope==='THIS_RESOURCE'&&selected.length!==1)||(scope==='SELECTED_RESOURCES'&&!selected.length)||(scope==='COLLECTION'&&!collectionId)){setError('Choose the sources KnowledgeOS should use.');return} setLoading(true); try { const response=await askKnowledge({sessionId:active?.id,question,scope,resourceId:scope==='THIS_RESOURCE'?selected[0]:undefined,resourceIds:scope==='SELECTED_RESOURCES'?selected:undefined,collectionId:scope==='COLLECTION'?collectionId:undefined}); setQuestion(''); await open(response.sessionId); await load() } catch {setError('KnowledgeOS could not answer right now.')} finally {setLoading(false)} }
  function newChat(){setActive(null);setQuestion('');setError('')}
  return <section className="kos-page kos-ask"><p className="kos-kicker">ASK KNOWLEDGEOS</p><h1>Ask what your sources can answer.</h1><div className="kos-ask-layout"><aside className="kos-chat-history"><button className="kos-button" onClick={newChat}>New conversation</button><h2>Recent conversations</h2>{sessions.length?sessions.map(session=><button key={session.id} className={active?.id===session.id?'is-active':''} onClick={()=>open(session.id)}>{session.title}</button>):<p>No saved conversations yet.</p>}</aside><div><form className="kos-ask-stage" onSubmit={submit}><BrainCircuit size={30}/><label>Scope<select id="ask-scope" name="scope" value={scope} onChange={event=>{setScope(event.target.value as Scope);setSelected([]);setCollectionId(undefined);setActive(null)}}><option value="LIBRARY">Entire library</option><option value="THIS_RESOURCE">One resource</option><option value="SELECTED_RESOURCES">Selected resources</option><option value="COLLECTION">Collection</option></select></label>{scope==='COLLECTION'&&<label>Collection<select id="ask-collection" name="collectionId" value={collectionId??''} onChange={event=>setCollectionId(Number(event.target.value)||undefined)}><option value="">Choose collection</option>{collections.map(collection=><option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label>}{(scope==='THIS_RESOURCE'||scope==='SELECTED_RESOURCES')&&<div className="kos-resource-picker">{resources.map(resource=><label key={resource.id}><input name="resourceIds" type={scope==='THIS_RESOURCE'?'radio':'checkbox'} checked={selected.includes(resource.id)} onChange={()=>scope==='THIS_RESOURCE'?setSelected([resource.id]):toggle(resource.id)}/>{resource.title}</label>)}</div>}<label>Your question<textarea id="ask-question" name="question" value={question} onChange={event=>setQuestion(event.target.value)} placeholder="What would you like to understand?" required/></label>{error&&<p className="kos-error">{error}</p>}<button className="kos-button kos-button--primary" disabled={loading}>{loading?'Finding evidence...':<>Ask sources <Send size={16}/></>}</button></form><div className="kos-answer">{active?.messages.length?active.messages.map(message=><article key={message.id}><p className="kos-kicker">{message.role==='USER'?'YOU':'KNOWLEDGEOS'}</p><p>{message.content}</p>{message.citations.map(citation=><details key={citation.chunkId}><summary>[{citation.citationOrder}] {citation.resourceTitle}</summary><p>{citation.evidenceExcerpt}</p></details>)}</article>):<p>Start a grounded conversation with your library.</p>}</div></div></div></section>
}
