import {
  ArrowRight,
  BookOpenText,
  BrainCircuit,
  CircleUserRound,
  Compass,
  FolderTree,
  Library,
  Network,
  ShieldCheck,
  Sparkles,
} from 'lucide-react'
import { Link } from 'react-router-dom'

const guideSections = [
  {
    id: 'collect-organize',
    number: '01',
    title: 'Collect and organize',
    icon: Library,
    intro: 'Library is the source of truth for files and notes. Add material once, then use collections, tags, and semantic suggestions to keep it findable.',
    points: [
      'Import PDF, DOCX, TXT, or Markdown files, or create a note directly in Library.',
      'Processing moves through visible states such as uploading, parsing, chunking, embedding, ready, or failed. Failed resources can be retried without hiding the reason.',
      'Use search, filters, selection, and bulk actions to work with more than one resource.',
      'Collections and tags are explicit organization. Semantic Organization proposes relevant tags and collections for review; it does not silently replace your choices.',
    ],
    link: '/library',
    action: 'Open Library',
  },
  {
    id: 'understand',
    number: '02',
    title: 'Understand a source',
    icon: BookOpenText,
    intro: 'Every ready resource has a Workspace 2.0 surface for reading persisted understanding and moving into study or questions.',
    points: [
      'Overview shows the document brief, key ideas, source context, notes, and organization controls when that data is available.',
      'Deep Dive connects a source to its Learning Areas and shows progress counts. It does not create a new learning path simply by opening the page.',
      'Knowledge Map shows stored collection membership, tags, and bounded related-resource links. It is not a claim that every idea in the library has been mapped.',
      'Understanding states can be current, stale, unsupported, failed, or unavailable. KnowledgeOS keeps these limits visible instead of inventing missing summaries.',
    ],
    link: '/library',
    action: 'Choose a source',
  },
  {
    id: 'ask',
    number: '03',
    title: 'Ask with evidence',
    icon: BrainCircuit,
    intro: 'Ask retrieves from a scope you choose and keeps citations beside the generated answer so you can inspect the evidence.',
    points: [
      'Choose one resource, selected resources, one collection, or the full library. “Ask this source” opens the same flow with that resource already scoped.',
      'Typed query planning selects the actual backend mode: structured, semantic, hybrid, or filtered hybrid. Hybrid retrieval combines semantic and keyword evidence, then uses reciprocal rank fusion before parent context is expanded from precise child chunks.',
      'The live server-sent event trace reports the mode and stages the backend actually ran. It is operational evidence, not a hidden chain of thought.',
      'Citations open the stored evidence excerpt. A citation supports verification, but you should still compare important claims with the source.',
      'AI Usage is local application telemetry for completed, failed, and rate-limited requests. It cannot report an exact Gemini balance, quota, or reset time.',
    ],
    link: '/ask',
    action: 'Open Ask',
  },
  {
    id: 'focus',
    number: '04',
    title: 'Turn sources into learning',
    icon: Sparkles,
    intro: 'Focus converts a collection into a durable learning structure while preserving work you have already completed.',
    points: [
      'The structure is Collection to Learning Area to Learning Path to Module to Concept to Recall.',
      'Build a Learning Area from ready resources in a collection. Primary and supporting sources keep evidence roles explicit.',
      'When collection knowledge changes, the path can become stale. Refresh adds valid evidence and retires unsupported concepts without deleting mastery or Recall history.',
      'Recall records answers and explanations against concepts. Legacy learning topics remain available where the product has preserved them.',
      'A Learning Area is not generated by simply viewing it. Build and refresh are deliberate actions.',
    ],
    link: '/focus',
    action: 'Open Focus',
  },
  {
    id: 'return',
    number: '05',
    title: 'Return without losing context',
    icon: Compass,
    intro: 'Home is the re-entry point for work already in motion.',
    points: [
      'Resume opens the most recent supported activity at its stored destination.',
      'Recent Activity lists additional source, Ask, and Focus work when available.',
      'If activity is unavailable, Home keeps Library and the four primary workflows accessible instead of blocking the account.',
    ],
    link: '/dashboard',
    action: 'Go Home',
  },
  {
    id: 'account',
    number: '06',
    title: 'Account and privacy',
    icon: ShieldCheck,
    intro: 'Profile contains the small set of identity and security controls needed for a personal knowledge workspace.',
    points: [
      'Change your display name, add or remove an optional avatar, and change your password with the current password.',
      'Without an avatar, KnowledgeOS uses deterministic initials from your display name. Removing an image does not make the profile incomplete.',
      'Signed-in requests are scoped to the current account. Ask answers are grounded in retrieved library evidence and expose citations when evidence is used.',
      'Account identity, avatar state, and password controls remain separate from your library content and learning progress.',
    ],
    link: '/profile',
    action: 'Open Profile',
  },
]

export default function KnowledgeGuidePage() {
  return <section className="kos-page kos-guide-page">
    <header className="kos-guide-hero">
      <div><p className="kos-kicker">KNOWLEDGEOS GUIDE</p><h1>A practical loop for your knowledge.</h1><p>Collect what matters, organize it, understand the source, retrieve grounded answers, and learn through Focus. This guide describes the product as it works today.</p></div>
      <div className="kos-guide-loop" aria-label="Knowledge workflow">
        {['Collect', 'Organize', 'Understand', 'Retrieve and Ask', 'Learn'].map((step, index) => <span key={step}><b>{String(index + 1).padStart(2, '0')}</b>{step}{index < 4 && <ArrowRight size={14} aria-hidden="true" />}</span>)}
      </div>
    </header>

    <div className="kos-guide-layout">
      <nav className="kos-guide-toc" aria-label="Guide contents">
        <p>IN THIS GUIDE</p>
        {guideSections.map(section => { const Icon = section.icon; return <a key={section.id} href={`#${section.id}`}><Icon size={16} aria-hidden="true" /><span>{section.title}</span></a> })}
      </nav>

      <main className="kos-guide-content">
        <section className="kos-guide-start" aria-labelledby="quick-start-heading">
          <FolderTree size={20} aria-hidden="true" />
          <div><p className="kos-kicker">QUICK START</p><h2 id="quick-start-heading">A useful first session</h2><ol><li>Import one source in Library and wait for Ready.</li><li>Open its Workspace and review the persisted brief.</li><li>Use Ask this source and inspect at least one citation.</li><li>Add the source to a collection, then build or continue its Learning Area in Focus.</li></ol></div>
        </section>

        {guideSections.map(section => { const Icon = section.icon; return <article className="kos-guide-chapter" id={section.id} key={section.id}>
          <div className="kos-guide-chapter-index">{section.number}</div>
          <div className="kos-guide-chapter-body">
            <header><span><Icon size={18} aria-hidden="true" /></span><div><h2>{section.title}</h2><p>{section.intro}</p></div></header>
            <ul>{section.points.map(point => <li key={point}>{point}</li>)}</ul>
            <Link to={section.link}>{section.action}<ArrowRight size={15} aria-hidden="true" /></Link>
          </div>
        </article> })}

        <aside className="kos-guide-boundary">
          <Network size={20} aria-hidden="true" />
          <div><h2>Read the evidence, not the promise</h2><p>Semantic retrieval, learning paths, and knowledge maps help you navigate your own material. They do not guarantee complete coverage or make every generated statement correct. Use citations, source status, and stored relationships to judge what the system actually knows.</p></div>
        </aside>
      </main>
    </div>

    <footer className="kos-guide-footer"><CircleUserRound size={18} aria-hidden="true" /><p>Need account controls? Guide and Profile are secondary destinations, while Home, Library, Ask, and Focus remain the primary navigation.</p><Link to="/profile">Open Profile<ArrowRight size={15} aria-hidden="true" /></Link></footer>
  </section>
}
