import { Check, CircleHelp, Clock3, Copy, FileText, ListChecks, Loader2, Map, Maximize2, MessageSquare, MessageSquarePlus, Minimize2, Scale, SearchCheck, Send, Sparkles, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { getApiErrorMessage } from '../api/errors'
import { getAskUsage, getChatSession, getChatSessions, getCollections, getResources, preflightAsk, retryAskAttempt, startAskAttempt, subscribeAskTrace, type AiUsage, type AskAttempt, type AskInput, type AskPreflight, type AskTraceEvent, type ChatDetail, type ChatSession, type KnowledgeCollection, type Resource } from '../api/knowledge'
import MarkdownView from '../components/MarkdownView'
import RagExecutionTracePanel from '../components/RagExecutionTracePanel'

type Scope = 'THIS_RESOURCE' | 'SELECTED_RESOURCES' | 'COLLECTION' | 'LIBRARY'
const SMART_PROMPTS = [
  { id: 'roadmap', icon: Map, label: 'Roadmap kiến thức', prompt: 'Đưa cho tôi các đầu mục kiến thức chính của tài liệu này, đánh số thứ tự từ 1 đến hết như một lộ trình học tập.' },
  { id: 'compare', icon: Scale, label: 'So sánh & đối chiếu', prompt: 'So sánh và phân tích sự khác biệt giữa các giải pháp hoặc trường phái được nhắc đến trong tài liệu.' },
  { id: 'summary', icon: ListChecks, label: 'Tóm tắt 3 ý chính', prompt: 'Tóm tắt 3 luận điểm quan trọng nhất trong tài liệu này kèm từ khóa và ý nghĩa thực tiễn.' },
  { id: 'critique', icon: SearchCheck, label: 'Phản biện chuyên sâu', prompt: 'Chỉ ra các điểm mạnh, giới hạn kỹ thuật và rủi ro tiềm ẩn của phương pháp được trình bày.' },
]

export default function KnowledgeAskPage() {
  const [params] = useSearchParams(); const initial = Number(params.get('resource') || params.get('resources')); const sessionFromUrl = Number(params.get('session'))
  const [resources, setResources] = useState<Resource[]>([]); const [collections, setCollections] = useState<KnowledgeCollection[]>([]); const [sessions, setSessions] = useState<ChatSession[]>([])
  const [scope, setScope] = useState<Scope>(initial ? 'THIS_RESOURCE' : 'LIBRARY'); const [selected, setSelected] = useState<number[]>(initial ? [initial] : []); const [collectionId, setCollectionId] = useState<number | undefined>()
  const [active, setActive] = useState<ChatDetail | null>(null); const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [elapsedSec, setElapsedSec] = useState('0.0')
  const [copiedId, setCopiedId] = useState<number | null>(null); const [highlightedCitation, setHighlightedCitation] = useState<number | null>(null); const [zenMode, setZenMode] = useState(false)
  const [traceEvents, setTraceEvents] = useState<AskTraceEvent[]>([]); const [attempt, setAttempt] = useState<AskAttempt | null>(null); const [preflight, setPreflight] = useState<AskPreflight | null>(null); const [usage, setUsage] = useState<AiUsage | null>(null)
  const timerRef = useRef<number | null>(null); const streamCleanupRef = useRef<(() => void) | null>(null)

  const load = () => { Promise.allSettled([getResources(), getCollections(), getChatSessions(), getAskUsage()]).then(([res, col, sess, usageResult]) => { if (res.status === 'fulfilled') setResources(res.value.items); if (col.status === 'fulfilled') setCollections(col.value); if (sess.status === 'fulfilled') setSessions(sess.value); if (usageResult.status === 'fulfilled') setUsage(usageResult.value); if (res.status === 'rejected' && col.status === 'rejected' && sess.status === 'rejected') setError('Không thể tải Ask workspace. Hãy thử lại.') }) }
  useEffect(() => { load(); if (sessionFromUrl) void open(sessionFromUrl); return () => { if (timerRef.current) window.clearInterval(timerRef.current); streamCleanupRef.current?.() } }, [sessionFromUrl])
  const toggle = (id: number) => setSelected(values => values.includes(id) ? values.filter(value => value !== id) : [...values, id])
  async function open(id: number) { try { const detail = await getChatSession(id); setActive(detail); setScope(detail.scope as Scope); setSelected(detail.resourceIds); setCollectionId(detail.collectionId || undefined); setError('') } catch { setError('Không thể khôi phục cuộc hội thoại này.') } }
  function startTimer() { const start = Date.now(); setElapsedSec('0.0'); if (timerRef.current) window.clearInterval(timerRef.current); timerRef.current = window.setInterval(() => setElapsedSec(((Date.now() - start) / 1000).toFixed(1)), 100) }
  function stopTimer() { if (timerRef.current) { window.clearInterval(timerRef.current); timerRef.current = null } }
  function buildInput(value = question): AskInput { return { sessionId: active?.id, question: value, scope, resourceId: scope === 'THIS_RESOURCE' ? selected[0] : undefined, resourceIds: scope === 'SELECTED_RESOURCES' ? selected : undefined, collectionId: scope === 'COLLECTION' ? collectionId : undefined } }
  function validScope() { return !((scope === 'THIS_RESOURCE' && selected.length !== 1) || (scope === 'SELECTED_RESOURCES' && !selected.length) || (scope === 'COLLECTION' && !collectionId)) }

  async function submit(event: React.FormEvent) { event.preventDefault(); if (!question.trim()) return; setError(''); if (!validScope()) { setError('Hãy chọn đúng phạm vi nguồn trước khi hỏi.'); return } try { const input = buildInput(); if (!preflight || preflightQuestion !== question.trim()) { const estimate = await preflightAsk(input); setPreflight(estimate); setPreflightQuestion(question.trim()); if (estimate.heavy) return } await begin(input) } catch (err) { setError(getApiErrorMessage(err, 'Không thể kiểm tra câu hỏi lúc này.')) } }
  const [preflightQuestion, setPreflightQuestion] = useState('')
  async function begin(input: AskInput) { setPreflight(null); setPreflightQuestion(''); setError(''); setLoading(true); setTraceEvents([]); startTimer(); try { const started = await startAskAttempt(input); setAttempt(started); await open(started.sessionId); streamCleanupRef.current?.(); streamCleanupRef.current = subscribeAskTrace(started.attemptId, event => { setTraceEvents(events => [...events.filter(item => item.sequence !== event.sequence), event].sort((a, b) => a.sequence - b.sequence)); if (event.status === 'COMPLETE' || event.status === 'FAILED') { setLoading(false); stopTimer(); void open(started.sessionId); void load(); if (event.status === 'COMPLETE') setQuestion(''); else setError(failureMessage(event.technicalDetails.failureCategory)); streamCleanupRef.current?.(); streamCleanupRef.current = null } }, () => setError('Live trace đang kết nối lại; lượt hỏi vẫn được giữ nguyên.')) } catch (err) { stopTimer(); setLoading(false); setError(getApiErrorMessage(err, 'Không thể bắt đầu lượt hỏi.')) } }
  async function retry() { if (!attempt || attempt.status !== 'FAILED') return; setError(''); setLoading(true); startTimer(); try { const next = await retryAskAttempt(attempt.attemptId); setAttempt(next); const detail = await getChatSession(next.sessionId); setActive(detail); streamCleanupRef.current?.(); streamCleanupRef.current = subscribeAskTrace(next.attemptId, event => { setTraceEvents(events => [...events.filter(item => item.sequence !== event.sequence), event].sort((a, b) => a.sequence - b.sequence)); if (event.status !== 'RUNNING') { setLoading(false); stopTimer(); void open(next.sessionId); void load(); if (event.status === 'COMPLETE') setError(''); else setError(failureMessage(event.technicalDetails.failureCategory)); streamCleanupRef.current?.(); streamCleanupRef.current = null } }, () => setError('Live trace đang kết nối lại; lượt hỏi vẫn được giữ nguyên.')) } catch (err) { stopTimer(); setLoading(false); setError(getApiErrorMessage(err, 'Không thể thử lại câu hỏi.')) } }
  function failureMessage(category: string | null) { if (category === 'RATE_LIMIT') return 'Provider đang giới hạn tốc độ hoặc quota. KnowledgeOS không biết số dư/reset chính xác; hãy chờ rồi thử lại.'; if (category === 'TIMEOUT') return 'Provider phản hồi quá lâu. Câu hỏi vẫn được giữ lại để thử lại.'; if (category === 'RETRIEVAL') return 'Không thể truy xuất nguồn cho lượt hỏi này. Câu hỏi vẫn được giữ lại.'; return 'Lượt hỏi chưa hoàn tất. Câu hỏi vẫn được giữ lại để thử lại.' }
  function newChat() { streamCleanupRef.current?.(); setActive(null); setAttempt(null); setQuestion(''); setError(''); setTraceEvents([]); setPreflight(null); setElapsedSec('0.0') }
  function handlePrompt(prompt: string) { setQuestion(prompt); setPreflight(null); setPreflightQuestion(''); document.getElementById('ask-question')?.focus() }
  function copyMessage(id: number, content: string) { void navigator.clipboard.writeText(content); setCopiedId(id); window.setTimeout(() => setCopiedId(null), 2000) }
  function handleCitationClick(number: number) { setHighlightedCitation(number); const el = document.getElementById(`citation-detail-${number}`); if (el) { (el as HTMLDetailsElement).open = true; el.scrollIntoView({ behavior: 'smooth', block: 'nearest' }) }; window.setTimeout(() => setHighlightedCitation(null), 2500) }

  return <section className={`kos-page kos-ask ${zenMode ? 'kos-zen-mode' : ''}`}>
    <div className="kos-page-header"><div><p className="kos-kicker">ASK WORKSPACE 2.0</p><h1>Hỏi từ những gì thư viện đã biết.</h1><p className="kos-ask-dek">Một không gian hỏi đáp có phạm vi rõ ràng, dấu vết truy xuất trực tiếp và trích dẫn đối chứng.</p></div><button type="button" className="kos-button kos-button--ghost kos-zen-toggle" onClick={() => setZenMode(value => !value)}>{zenMode ? <><Minimize2 size={15} /> Giao diện chuẩn</> : <><Maximize2 size={15} /> Tập trung đọc</>}</button></div>
    <div className="kos-ask-layout">
      {!zenMode && <aside className="kos-ask-sidebar"><div className="kos-ask-box kos-new-chat-box"><button className="kos-button kos-button--primary kos-button--block" onClick={newChat}><MessageSquarePlus size={16} /> Cuộc hội thoại mới</button></div>
        <div className="kos-ask-box kos-recent-box"><div className="kos-box-header"><div className="kos-box-title"><MessageSquare size={15} /><span>Gần đây</span></div>{sessions.length > 0 && <span className="kos-box-badge">{sessions.length}</span>}</div><div className="kos-recent-scroll-content">{sessions.length ? sessions.map(item => <button key={item.id} className={`kos-recent-item ${active?.id === item.id ? 'is-active' : ''}`} onClick={() => void open(item.id)}><span className="kos-recent-bullet">•</span><span className="kos-recent-text">{item.title || 'Untitled conversation'}</span></button>) : <p className="kos-box-empty">Chưa có cuộc hội thoại.</p>}</div></div>
        <div className="kos-ask-box kos-usage-box"><div className="kos-box-header"><div className="kos-box-title"><Clock3 size={15} /><span>Local usage</span></div><span className="kos-box-badge">{usage?.providerQuotaState || 'UNKNOWN'}</span></div><p className="kos-usage-caption">Số liệu ghi nhận từ KnowledgeOS, không phải số dư provider.</p><div className="kos-usage-grid"><span>Completed</span><strong>{usage?.completedRequests ?? 0}</strong><span>Rate limited</span><strong>{usage?.rateLimitCount ?? 0}</strong><span>Total tokens</span><strong>{usage?.totalTokens || '—'}</strong></div><small>Quota exact: unavailable · Reset: unknown</small></div>
        <RagExecutionTracePanel events={traceEvents} loading={loading} scope={scope} citationCount={active?.messages.at(-1)?.citations.length || 0} /></aside>}
      <div className="kos-ask-stage"><form className="kos-ask-form" onSubmit={submit}><div className="kos-ask-scope"><div className="kos-form-heading"><Sparkles size={16} /><span>Phạm vi truy xuất</span><small>{scope === 'LIBRARY' ? 'toàn bộ thư viện' : scope === 'COLLECTION' ? 'một collection' : scope === 'THIS_RESOURCE' ? 'một resource' : 'các resource đã chọn'}</small></div><select name="scope" value={scope} onChange={event => { setScope(event.target.value as Scope); setPreflight(null) }}><option value="LIBRARY">Toàn bộ thư viện</option><option value="COLLECTION">Một collection</option><option value="THIS_RESOURCE">Một resource</option><option value="SELECTED_RESOURCES">Các resource đã chọn</option></select></div>
        {scope === 'COLLECTION' && <label>Collection<select name="collectionId" value={collectionId || ''} onChange={event => setCollectionId(Number(event.target.value))} required><option value="">Chọn collection</option>{collections.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
        {(scope === 'THIS_RESOURCE' || scope === 'SELECTED_RESOURCES') && <fieldset className="kos-resource-picker"><legend>Sources</legend>{resources.map(resource => <label key={resource.id}><input type={scope === 'THIS_RESOURCE' ? 'radio' : 'checkbox'} checked={selected.includes(resource.id)} onChange={() => scope === 'THIS_RESOURCE' ? setSelected([resource.id]) : toggle(resource.id)} /> <FileText size={14} /> <span>{resource.title}</span></label>)}</fieldset>}
        <label>Your question<textarea id="ask-question" name="question" value={question} onChange={event => { setQuestion(event.target.value); setPreflight(null) }} placeholder="Hỏi một câu cụ thể về nguồn đã chọn..." required /></label>
        <div className="kos-prompt-pills-bar"><span className="kos-pills-title"><CircleHelp size={13} /> Gợi ý bắt đầu</span><div className="kos-pills-container">{SMART_PROMPTS.map(item => { const Icon = item.icon; return <button key={item.id} type="button" className="kos-prompt-pill" onClick={() => handlePrompt(item.prompt)}><Icon size={14} /><span>{item.label}</span></button> })}</div></div>
        {preflight?.heavy && <div className="kos-preflight-warning"><div><strong>Câu hỏi này có thể cần nhiều ngữ cảnh.</strong><p>Ước tính cục bộ: khoảng {preflight.estimatedInputTokens.toLocaleString()} input tokens và {preflight.estimatedContextCharacters.toLocaleString()} ký tự context. Đây là heuristic, không phải quota provider.</p></div><button type="button" className="kos-icon-button" onClick={() => setPreflight(null)} aria-label="Bỏ cảnh báo"><X size={16} /></button><button type="button" className="kos-button kos-button--secondary" onClick={() => void begin(buildInput())}>Tiếp tục hỏi</button></div>}
        {error && <p className="kos-error">{error}</p>}
        <button className="kos-button kos-button--primary kos-ask-submit" disabled={loading || Boolean(preflight?.heavy)}>{loading ? <><Loader2 size={16} className="kos-btn-spin" /> Đang truy xuất bằng chứng… {elapsedSec}s</> : <>Hỏi KnowledgeOS <Send size={16} /></>}</button>
      </form>
      <div className="kos-answer">{active?.messages.length ? active.messages.map(message => <article key={message.id} className={`kos-message-article kos-message--${message.role.toLowerCase()} ${message.status === 'FAILED' ? 'is-failed' : ''}`}><div className="kos-message-header"><p className="kos-kicker">{message.role === 'USER' ? 'YOU' : 'KNOWLEDGEOS'} {message.status === 'FAILED' && <span className="kos-status-chip">FAILED · {message.failureCategory || 'UNKNOWN'}</span>}</p>{message.role === 'ASSISTANT' && <button type="button" className="kos-copy-btn" onClick={() => copyMessage(message.id, message.content)}>{copiedId === message.id ? <><Check size={13} /> Đã chép</> : <><Copy size={13} /> Sao chép</>}</button>}{message.status === 'FAILED' && attempt?.userMessageId === message.id && <button type="button" className="kos-button kos-button--secondary kos-retry-button" onClick={() => void retry()} disabled={loading}>Thử lại câu hỏi</button>}</div><div className="kos-message-body"><MarkdownView content={message.content} onCitationClick={handleCitationClick} /></div>{message.citations.length > 0 && <div className="kos-citations-section"><p className="kos-citations-heading"><Sparkles size={13} /> Bằng chứng đã đối chiếu</p>{message.citations.map(citation => <details id={`citation-detail-${citation.citationOrder}`} key={citation.chunkId} className={`kos-citation-details ${highlightedCitation === citation.citationOrder ? 'kos-citation-glow' : ''}`}><summary><span className="kos-cit-num">[{citation.citationOrder}]</span><span className="kos-cit-title">{citation.resourceTitle}</span></summary><p className="kos-cit-excerpt">{citation.evidenceExcerpt}</p></details>)}</div>}</article>) : <div className="kos-answer-empty"><p>Đặt một câu hỏi có phạm vi rõ ràng. KnowledgeOS sẽ cho bạn thấy hệ thống đã thực sự chạy những bước nào.</p></div>}</div></div>
    </div>
  </section>
}
