package com.groupsync.backend.tournament.service;
import java.util.List;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.groupsync.backend.auth.security.AuthenticatedUser; import com.groupsync.backend.badminton.dto.MatchRequests.CreateMatchRequest; import com.groupsync.backend.badminton.model.*; import com.groupsync.backend.badminton.repository.*; import com.groupsync.backend.badminton.service.MatchService; import com.groupsync.backend.group.model.GroupRole; import com.groupsync.backend.group.repository.MembershipRepository; import com.groupsync.backend.shared.exception.*; import com.groupsync.backend.tournament.dto.*; import com.groupsync.backend.tournament.model.*; import com.groupsync.backend.tournament.repository.*; import com.groupsync.backend.user.repository.UserAccountRepository;
@Service public class TournamentService {
 private final TournamentRepository tournaments; private final TournamentParticipantRepository participants; private final TournamentMatchRepository tournamentMatches; private final MembershipRepository memberships; private final SeasonRepository seasons; private final BadmintonSessionRepository sessions; private final BadmintonMatchRepository badmintonMatches; private final UserAccountRepository users; private final MatchService matches;
 public TournamentService(TournamentRepository tournaments,TournamentParticipantRepository participants,TournamentMatchRepository tournamentMatches,MembershipRepository memberships,SeasonRepository seasons,BadmintonSessionRepository sessions,BadmintonMatchRepository badmintonMatches,UserAccountRepository users,MatchService matches){this.tournaments=tournaments;this.participants=participants;this.tournamentMatches=tournamentMatches;this.memberships=memberships;this.seasons=seasons;this.sessions=sessions;this.badmintonMatches=badmintonMatches;this.users=users;this.matches=matches;}
 @Transactional(readOnly=true) public List<TournamentResponses.Tournament> list(AuthenticatedUser actor,Long groupId){member(groupId,actor.getId());return tournaments.findByGroupIdOrderByCreatedAtDesc(groupId).stream().map(t->TournamentResponses.Tournament.from(t,(int)participants.countByTournamentId(t.getId()))).toList();}
 @Transactional public TournamentResponses.Tournament create(AuthenticatedUser actor,Long groupId,TournamentRequests.Create request){organizer(groupId,actor.getId());var season=seasons.findById(request.seasonId()).filter(s->s.getGroup().getId().equals(groupId)).orElseThrow(()->new NotFoundException("Season not found."));var session=sessions.findById(request.sessionId()).filter(s->s.getGroup().getId().equals(groupId)&&s.getSeason().getId().equals(season.getId())).orElseThrow(()->new NotFoundException("Badminton session not found.")); if(!request.format().equals("KNOCKOUT")&&!request.format().equals("GROUP_KNOCKOUT"))throw new BadRequestException("Tournament format is invalid.");var t=tournaments.save(new Tournament(session.getGroup(),season,session,request.name().trim(),request.format(),request.maxParticipants()));return TournamentResponses.Tournament.from(t,0);}
 @Transactional public TournamentResponses.Tournament open(AuthenticatedUser a,Long id){var t=organizerTournament(a,id);t.open();return view(t);} @Transactional public TournamentResponses.Tournament start(AuthenticatedUser a,Long id){var t=organizerTournament(a,id);if(participants.countByTournamentId(id)<2)throw new ConflictException("Tournament needs at least two participants.");t.start();return view(t);} @Transactional public TournamentResponses.Tournament complete(AuthenticatedUser a,Long id,Long championId){var t=organizerTournament(a,id);if(participants.findByTournamentIdAndUserId(id,championId).isEmpty())throw new ConflictException("Champion must be a tournament participant.");t.complete(users.findById(championId).orElseThrow());return view(t);}
 @Transactional public TournamentResponses.Participant register(AuthenticatedUser a,Long id,Long userId){var t=tournaments.findById(id).orElseThrow(()->new NotFoundException("Tournament not found."));member(t.getGroup().getId(),a.getId());if(t.getStatus()!=TournamentStatus.REGISTRATION_OPEN)throw new ConflictException("Tournament registration is closed.");if(participants.countByTournamentId(id)>=t.getMaxParticipants())throw new ConflictException("Tournament is full.");member(t.getGroup().getId(),userId);if(participants.findByTournamentIdAndUserId(id,userId).isPresent())throw new ConflictException("This user is already registered for the tournament.");return TournamentResponses.Participant.from(participants.save(new TournamentParticipant(t,users.findById(userId).orElseThrow())));}
 @Transactional(readOnly=true) public List<TournamentResponses.Participant> participants(AuthenticatedUser a,Long id){var t=tournaments.findById(id).orElseThrow(()->new NotFoundException("Tournament not found."));member(t.getGroup().getId(),a.getId());return participants.findByTournamentIdOrderByRegisteredAtAsc(id).stream().map(TournamentResponses.Participant::from).toList();}
 @Transactional public TournamentResponses.Bracket createMatch(AuthenticatedUser a,Long id,TournamentRequests.CreateTournamentMatch request){var t=organizerTournament(a,id);if(t.getStatus()!=TournamentStatus.IN_PROGRESS)throw new ConflictException("Tournament must be in progress.");var match=matches.create(a,t.getSession().getId(),request.match());TournamentStage stage=TournamentStage.valueOf(request.stage());return TournamentResponses.Bracket.from(tournamentMatches.save(new TournamentMatch(t,findMatch(match.id()),stage,request.matchNumber(),request.nextMatchNumber())));}
 @Transactional(readOnly=true) public List<TournamentResponses.Bracket> bracket(AuthenticatedUser a,Long id){var t=tournaments.findById(id).orElseThrow(()->new NotFoundException("Tournament not found."));member(t.getGroup().getId(),a.getId());return tournamentMatches.findByTournamentIdOrderByStageAscMatchNumberAsc(id).stream().map(TournamentResponses.Bracket::from).toList();}
 private com.groupsync.backend.badminton.model.BadmintonMatch findMatch(Long id){return badmintonMatches.findById(id).orElseThrow(()->new NotFoundException("Match not found."));}
 private TournamentResponses.Tournament view(Tournament t){return TournamentResponses.Tournament.from(t,(int)participants.countByTournamentId(t.getId()));} private Tournament organizerTournament(AuthenticatedUser a,Long id){var t=tournaments.findById(id).orElseThrow(()->new NotFoundException("Tournament not found."));organizer(t.getGroup().getId(),a.getId());return t;} private void organizer(Long gid,Long uid){if(member(gid,uid).getRole()==GroupRole.MEMBER)throw new ForbiddenException("Only owner or organizer can manage tournaments.");} private com.groupsync.backend.group.model.Membership member(Long gid,Long uid){return memberships.findByGroupIdAndUserId(gid,uid).orElseThrow(()->new ForbiddenException("You are not a member of this group."));}
}
