package com.groupsync.backend.badminton.service;

import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.groupsync.backend.auth.security.AuthenticatedUser;
import com.groupsync.backend.badminton.dto.MatchResponses;
import com.groupsync.backend.badminton.model.BadmintonMatch;
import com.groupsync.backend.badminton.model.BadmintonPlayerStat;
import com.groupsync.backend.badminton.model.BadmintonSession;
import com.groupsync.backend.badminton.model.RegistrationStatus;
import com.groupsync.backend.badminton.repository.BadmintonMatchRepository;
import com.groupsync.backend.badminton.repository.BadmintonPlayerStatRepository;
import com.groupsync.backend.badminton.repository.BadmintonRegistrationRepository;
import com.groupsync.backend.badminton.repository.RankingHistoryRepository;
import com.groupsync.backend.group.repository.MembershipRepository;
import com.groupsync.backend.shared.exception.ForbiddenException;
import com.groupsync.backend.shared.exception.NotFoundException;

@Service
public class StatisticsService {
    private final BadmintonPlayerStatRepository statRepository; private final BadmintonRegistrationRepository registrationRepository; private final BadmintonMatchRepository matchRepository; private final MembershipRepository membershipRepository; private final RankingHistoryRepository historyRepository;
    public StatisticsService(BadmintonPlayerStatRepository statRepository, BadmintonRegistrationRepository registrationRepository, BadmintonMatchRepository matchRepository, MembershipRepository membershipRepository, RankingHistoryRepository historyRepository) { this.statRepository = statRepository; this.registrationRepository = registrationRepository; this.matchRepository = matchRepository; this.membershipRepository = membershipRepository; this.historyRepository = historyRepository; }
    @Transactional public void recordAttendance(BadmintonSession session) { registrationRepository.findBySessionIdOrderByRegisteredAtAscIdAsc(session.getId()).stream().filter(r -> r.getStatus() == RegistrationStatus.CHECKED_IN || r.getStatus() == RegistrationStatus.NO_SHOW).forEach(r -> { BadmintonPlayerStat stat = statRepository.findByGroupIdAndSeasonIdAndUserId(session.getGroup().getId(), session.getSeason().getId(), r.getUser().getId()).orElseGet(() -> statRepository.save(new BadmintonPlayerStat(session.getGroup(), session.getSeason(), r.getUser()))); stat.recordAttendance(r.getStatus() == RegistrationStatus.NO_SHOW); statRepository.save(stat); }); }
    @Transactional(readOnly = true) public List<MatchResponses.Stat> leaderboard(AuthenticatedUser actor, Long groupId, Long seasonId) { requireMember(groupId, actor.getId()); return statRepository.findLeaderboard(groupId, seasonId).stream().map(s -> toStat(s, recentForm(s))).toList(); }
    @Transactional(readOnly = true) public MatchResponses.Stat player(AuthenticatedUser actor, Long groupId, Long seasonId, Long userId) { requireMember(groupId, actor.getId()); BadmintonPlayerStat stat = statRepository.findByGroupIdAndSeasonIdAndUserId(groupId, seasonId, userId).orElseThrow(() -> new NotFoundException("Player statistics not found.")); return toStat(stat, recentForm(stat)); }
    @Transactional(readOnly = true) public List<MatchResponses.History> history(AuthenticatedUser actor, Long groupId, Long seasonId, Long userId) { requireMember(groupId, actor.getId()); return historyRepository.findByGroupIdAndSeasonIdAndUserIdOrderByCreatedAtDesc(groupId, seasonId, userId).stream().map(h -> new MatchResponses.History(h.getId(), h.getMatch().getId(), h.getUser().getId(), h.getPointsAfter(), h.getWinsAfter(), h.getMatchesAfter(), h.getCreatedAt())).toList(); }
    @Transactional(readOnly = true) public MatchResponses.HeadToHead headToHead(AuthenticatedUser actor, Long groupId, Long seasonId, Long userId, Long opponentId) { requireMember(groupId, actor.getId()); int matches = 0, wins = 0; for (BadmintonMatch match : matches(groupId, seasonId)) { boolean hasUser = contains(match, userId), hasOpponent = contains(match, opponentId); if (!hasUser || !hasOpponent) continue; matches++; var userSide = match.getSides().stream().filter(s -> s.getParticipants().stream().anyMatch(p -> p.getUser().getId().equals(userId))).findFirst().orElseThrow(); if (userSide.getCode() == match.getWinnerSide()) wins++; } return new MatchResponses.HeadToHead(userId, opponentId, matches, wins, matches - wins); }
    @Transactional(readOnly = true) public List<MatchResponses.PartnerStat> partners(AuthenticatedUser actor, Long groupId, Long seasonId, Long userId) { requireMember(groupId, actor.getId()); Map<Long, int[]> values = new HashMap<>(); Map<Long, String> names = new HashMap<>(); for (BadmintonMatch match : matches(groupId, seasonId)) { for (var side : match.getSides()) if (side.getParticipants().stream().anyMatch(p -> p.getUser().getId().equals(userId))) { boolean win = side.getCode() == match.getWinnerSide(); side.getParticipants().stream().filter(p -> !p.getUser().getId().equals(userId)).forEach(p -> { values.computeIfAbsent(p.getUser().getId(), ignored -> new int[3]); int[] stat = values.get(p.getUser().getId()); stat[0]++; if (win) stat[1]++; else stat[2]++; names.put(p.getUser().getId(), p.getUser().getDisplayName()); }); } } return values.entrySet().stream().map(e -> new MatchResponses.PartnerStat(e.getKey(), names.get(e.getKey()), e.getValue()[0], e.getValue()[1], e.getValue()[2])).sorted((a, b) -> Integer.compare(b.matches(), a.matches())).toList(); }
    @Transactional(readOnly = true) public List<MatchResponses.Award> awards(AuthenticatedUser actor, Long groupId, Long seasonId, Long userId) { requireMember(groupId, actor.getId()); MatchResponses.Stat stat = player(actor, groupId, seasonId, userId); List<MatchResponses.Award> awards = new ArrayList<>(); if (stat.wins() > 0) awards.add(new MatchResponses.Award("FIRST_WIN", "First win", "This player has confirmed a winning match.")); List<MatchResponses.Stat> leaderboard = leaderboard(actor, groupId, seasonId); if (!leaderboard.isEmpty() && leaderboard.get(0).userId().equals(userId)) awards.add(new MatchResponses.Award("TOP_POINTS", "Top points", "This player currently leads the Season leaderboard.")); if (stat.attended() >= 3) awards.add(new MatchResponses.Award("RELIABLE", "Reliable attendee", "This player has attended at least three sessions.")); return awards; }
    private String recentForm(BadmintonPlayerStat stat) { return matchRepository.findBySessionGroupIdOrderByCreatedAtDesc(stat.getGroup().getId()).stream().filter(m -> m.getSeason().getId().equals(stat.getSeason().getId()) && m.getStatus() == com.groupsync.backend.badminton.model.MatchStatus.CONFIRMED).filter(m -> m.getSides().stream().anyMatch(side -> side.getParticipants().stream().anyMatch(p -> p.getUser().getId().equals(stat.getUser().getId())))).limit(5).map(m -> m.getSides().stream().filter(side -> side.getParticipants().stream().anyMatch(p -> p.getUser().getId().equals(stat.getUser().getId()))).findFirst().orElseThrow().getCode() == m.getWinnerSide() ? "W" : "L").reduce("", (a, b) -> a + b); }
    private List<BadmintonMatch> matches(Long groupId, Long seasonId) { return matchRepository.findBySessionGroupIdOrderByCreatedAtDesc(groupId).stream().filter(m -> m.getSeason().getId().equals(seasonId) && m.getStatus() == com.groupsync.backend.badminton.model.MatchStatus.CONFIRMED).toList(); }
    private boolean contains(BadmintonMatch match, Long userId) { return match.getSides().stream().flatMap(s -> s.getParticipants().stream()).anyMatch(p -> p.getUser().getId().equals(userId)); }
    private MatchResponses.Stat toStat(BadmintonPlayerStat s, String form) { double rate = s.getMatchesPlayed() == 0 ? 0 : (100.0 * s.getWins() / s.getMatchesPlayed()); return new MatchResponses.Stat(s.getUser().getId(), s.getUser().getDisplayName(), s.getMatchesPlayed(), s.getWins(), s.getLosses(), s.getPoints(), s.getAttended(), s.getNoShows(), rate, form); }
    private void requireMember(Long groupId, Long userId) { membershipRepository.findByGroupIdAndUserId(groupId, userId).orElseThrow(() -> new ForbiddenException("You are not a member of this group.")); }
}
