package com.groupsync.backend.knowledge.dto;

public enum AskTraceStage {
    QUERY_RECEIVED,
    PLAN_READY,
    FILTERS_APPLIED,
    STRUCTURED_OPERATION_COMPLETE,
    SEMANTIC_RETRIEVAL_COMPLETE,
    LEXICAL_RETRIEVAL_COMPLETE,
    RRF_COMPLETE,
    PARENT_CONTEXT_COMPLETE,
    CONTEXT_READY,
    GENERATION_STARTED,
    GENERATION_COMPLETE,
    CITATIONS_VERIFIED,
    COMPLETE,
    FAILED
}
