import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { getApiErrorMessage } from '../api/errors'
import { getGroups, type GroupSummary } from '../api/groups'
import {
  cancelBadmintonSession, checkInBadminton, confirmBadmintonSession, confirmMatch, createBadmintonSession, createMatch,
  generateAllocation, getBadmintonSeasons, getBadmintonSessions, getBadmintonVenues, getLeaderboard,
  getMatches, getNews, getPairings, joinBadmintonSession, leaveBadmintonSession, noShowBadminton,
  openBadmintonSession, startBadmintonSession, startMatch, submitMatchScore, type Allocation, type BadmintonSeason,
  type BadmintonSession, type Match, type News, type Pairing, type Stat, type Venue,
} from '../api/badminton'
import { useAuth } from '../auth/AuthContext'

function BadmintonPage() {
  const { user } = useAuth(); const [params] = useSearchParams()
  const [groups, setGroups] = useState<GroupSummary[]>([]); const [groupId, setGroupId] = useState(Number(params.get('groupId') ?? 0))
  const [seasons, setSeasons] = useState<BadmintonSeason[]>([]); const [venues, setVenues] = useState<Venue[]>([]); const [sessions, setSessions] = useState<BadmintonSession[]>([])
  const [allocations, setAllocations] = useState<Allocation[]>([]); const [pairings, setPairings] = useState<Pairing[]>([]); const [matches, setMatches] = useState<Match[]>([]); const [leaderboard, setLeaderboard] = useState<Stat[]>([]); const [news, setNews] = useState<News[]>([])
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [scores, setScores] = useState<Record<number, [string, string]>>({})
  const [title, setTitle] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [deadline, setDeadline] = useState(''); const [venueId, setVenueId] = useState(0); const [courtId, setCourtId] = useState(0); const [capacity, setCapacity] = useState('16')
  const badmintonGroups = groups.filter((g) => g.type === 'BADMINTON'); const selectedGroup = groups.find((g) => g.id === groupId); const selectedVenue = venues.find((v) => v.id === venueId); const organizer = selectedGroup?.role === 'OWNER' || selectedGroup?.role === 'ORGANIZER'

  async function refresh() {
    if (!groupId) return
    const [nextSessions, nextSeasons, nextVenues, nextMatches, nextNews] = await Promise.all([getBadmintonSessions(groupId), getBadmintonSeasons(groupId), getBadmintonVenues(groupId), getMatches(groupId), getNews(groupId)])
    setSessions(nextSessions); setSeasons(nextSeasons); setVenues(nextVenues); setMatches(nextMatches); setNews(nextNews)
    if (nextSeasons[0]) getLeaderboard(groupId, nextSeasons[0].id).then(setLeaderboard).catch(() => setLeaderboard([]))
    if (!venueId && nextVenues[0]) setVenueId(nextVenues[0].id); if (!courtId && nextVenues[0]?.courts[0]) setCourtId(nextVenues[0].courts[0].id)
  }
  useEffect(() => { getGroups().then((data) => { setGroups(data); if (!groupId) setGroupId(data.find((g) => g.type === 'BADMINTON')?.id ?? 0) }).catch((e) => setError(getApiErrorMessage(e, 'Could not load groups.'))) }, [])
  useEffect(() => { refresh().catch((e) => setError(getApiErrorMessage(e, 'Could not load badminton data.'))) }, [groupId])
  async function act(fn: () => Promise<unknown>, text: string) { setError(''); try { const result = await fn(); if (Array.isArray(result) && result.length > 0 && 'players' in result[0]) setAllocations(result as Allocation[]); setMessage(text); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Badminton action failed.')) } }
  async function create(event: React.FormEvent) { event.preventDefault(); try { await createBadmintonSession(groupId, { title, start: new Date(start).toISOString(), end: new Date(end).toISOString(), registrationDeadline: new Date(deadline).toISOString(), capacity: Number(capacity) || 16, seasonId: seasons[0]?.id, venueId, courtIds: [courtId] }); setMessage('Badminton session created as draft.'); setTitle(''); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not create session.')) } }
  async function makeMatch(pairing: Pairing) { const playing = sessions.find((s) => s.status === 'PLAYING'); if (!playing) return; try { await createMatch(playing.id, { courtId: pairing.courtId, roundNumber: pairing.roundNumber, sideAUserIds: pairing.sideA.map((p) => p.userId), sideBUserIds: pairing.sideB.map((p) => p.userId) }); setMessage('Match created from pairing suggestion.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not create match.')) } }
  async function score(match: Match) { const [a, b] = scores[match.id] ?? ['', '']; await act(() => submitMatchScore(match.id, Number(a), Number(b)), 'Score submitted.'); }

  return <section><div className="page-heading"><div><p className="eyebrow">Badminton operations</p><h1>Play sessions</h1><p className="intro">Checked-in players move from courts to pairings, matches and confirmed results. W/L, points and news are derived automatically.</p></div><select className="group-picker" value={groupId} onChange={(e) => setGroupId(Number(e.target.value))}>{badmintonGroups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></div>
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}{!groupId && <div className="page-panel empty-state">Create or join a BADMINTON group first.</div>}
    {groupId && <><div className="content-grid"><div><div className="section-title">Sessions</div>{sessions.length === 0 && <div className="page-panel empty-state">No badminton sessions yet.</div>}{sessions.map((s) => { const mine = s.registrations.find((r) => r.userId === user?.id); const checked = s.registrations.filter((r) => r.status === 'CHECKED_IN'); return <div className="page-panel study-card" key={s.id}><div className="study-card-header"><div><span className="source-tag source-badminton">{s.status}</span><h2>{s.title}</h2><p>{new Date(s.start).toLocaleString()} – {new Date(s.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p><p>{s.venueName} · {s.courts.map((c) => c.name).join(', ')}</p></div><span className="subtle">{s.registrations.filter((r) => r.status === 'REGISTERED' || r.status === 'CHECKED_IN').length} / {s.capacity}</span></div><div className="study-actions">{s.status === 'DRAFT' && organizer && <button className="btn btn-outline-primary" onClick={() => act(() => openBadmintonSession(s.id), 'Session opened.')}>Open</button>}{s.status === 'OPEN' && organizer && <button className="btn btn-primary" onClick={() => act(() => confirmBadmintonSession(s.id), 'Session confirmed.')}>Confirm</button>}{s.status === 'CONFIRMED' && organizer && <button className="btn btn-primary" onClick={() => act(() => startBadmintonSession(s.id), 'Session started.')}>Start</button>}{s.status === 'PLAYING' && organizer && <button className="btn btn-outline-success" onClick={() => act(() => generateAllocation(s.id), 'Courts allocated to checked-in players.')}>Allocate courts</button>}{(s.status === 'OPEN' || s.status === 'CONFIRMED') && !mine && <button className="btn btn-outline-primary" onClick={() => act(() => joinBadmintonSession(s.id), 'Joined; any calendar conflict is a warning.')}>Join</button>}{(s.status === 'OPEN' || s.status === 'CONFIRMED') && mine && mine.status !== 'CANCELLED' && <button className="btn btn-outline-secondary" onClick={() => act(() => leaveBadmintonSession(s.id), 'Registration cancelled; waitlist checked.')}>Leave</button>}{(s.status === 'OPEN' || s.status === 'CONFIRMED') && organizer && <button className="btn btn-outline-danger" onClick={() => act(() => cancelBadmintonSession(s.id), 'Session cancelled.')}>Cancel</button>}</div><div className="participant-pills">{s.registrations.filter((r) => r.status !== 'CANCELLED').map((r) => <span key={r.id}>{r.displayName} · {r.status}{r.conflictWarning ? ' · conflict warning' : ''}{organizer && r.status === 'REGISTERED' && <><button className="mini-button" onClick={() => act(() => checkInBadminton(s.id, r.userId), 'Player checked in.')}>check in</button><button className="mini-button" onClick={() => act(() => noShowBadminton(s.id, r.userId), 'Player marked no-show.')}>no-show</button></>}</span>)}</div><p className="hint">Checked in: {checked.length}. Generate allocation only after check-in.</p></div>})}</div>
      <form className="page-panel form-stack" onSubmit={create}><div><p className="eyebrow">Organizer</p><h2>Create session</h2></div><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Starts<input type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} required /></label><label>Ends<input type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} required /></label><label>Registration deadline<input type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} required /></label><label>Capacity<input type="number" min="1" value={capacity} onChange={(e) => setCapacity(e.target.value)} /></label><label>Venue<select value={venueId} onChange={(e) => setVenueId(Number(e.target.value))}>{venues.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Court<select value={courtId} onChange={(e) => setCourtId(Number(e.target.value))}>{selectedVenue?.courts.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn btn-primary" disabled={!seasons[0] || !venueId || !courtId}>Create draft</button></form></div>
      <div className="content-grid dashboard-grid"><div className="page-panel"><div className="section-title">Court allocation and pairing preview</div>{allocations.map((a) => <div className="saved-source" key={a.id}><strong>{a.courtName}: {a.players.map((p) => p.displayName).join(', ') || 'no checked-in players'}</strong><span>{a.status}</span></div>)}{sessions.filter((s) => s.status === 'PLAYING').map((s) => <div key={s.id}><button className="btn btn-outline-primary" onClick={() => getPairings(s.id).then(setPairings).catch((e) => setError(getApiErrorMessage(e, 'Could not load pairings.')))}>Suggest balanced pairing</button>{pairings.map((p) => <div className="saved-source" key={`${p.courtId}-${p.roundNumber}`}><strong>{p.courtName}: {p.sideA.map((x) => x.displayName).join(' + ')} vs {p.sideB.map((x) => x.displayName).join(' + ')}</strong><span>{p.unassigned.length} unassigned</span><button className="mini-button" onClick={() => makeMatch(p)}>Create match</button></div>)}</div>)}</div><div className="page-panel"><div className="section-title">Leaderboard</div>{leaderboard.length === 0 && <p className="hint">Results will appear here after a confirmed match.</p>}{leaderboard.map((s) => <div className="member-row" key={s.userId}><strong>{s.displayName}</strong><span>{s.points} pts · {s.wins}W/{s.losses}L · {s.recentForm || '—'}</span></div>)}</div></div>
      <div className="page-panel"><div className="section-title">Matches and results</div>{matches.length === 0 && <p className="hint">No matches yet.</p>}{matches.map((m) => <div className="study-card" key={m.id}><div className="study-card-header"><strong>{m.courtName} · Round {m.roundNumber} · {m.status}</strong><span>{m.scoreA ?? '—'} : {m.scoreB ?? '—'}</span></div><p>{m.sides.map((side) => `${side.code}: ${side.participants.map((p) => p.displayName).join(' + ')}`).join(' · ')}</p><div className="study-actions">{m.status === 'SCHEDULED' && organizer && <button className="btn btn-outline-primary" onClick={() => act(() => startMatch(m.id), 'Match started.')}>Start</button>}{m.status === 'PLAYING' && <><input className="score-input" type="number" min="0" placeholder="A" onChange={(e) => setScores({ ...scores, [m.id]: [e.target.value, scores[m.id]?.[1] ?? ''] })} /><input className="score-input" type="number" min="0" placeholder="B" onChange={(e) => setScores({ ...scores, [m.id]: [scores[m.id]?.[0] ?? '', e.target.value] })} /><button className="btn btn-primary" onClick={() => score(m)}>Submit score</button></>}{m.status === 'RESULT_SUBMITTED' && organizer && <button className="btn btn-primary" onClick={() => act(() => confirmMatch(m.id), 'Result confirmed; stats and news updated.')}>Confirm result</button>}</div></div>)}</div>
      <div className="page-panel"><div className="section-title">Group news</div>{news.length === 0 && <p className="hint">No announcements or results yet.</p>}{news.map((n) => <div className="saved-source" key={n.id}><strong>{n.title}</strong><span>{n.content}</span></div>)}</div>
    </>}
  </section>
}
export default BadmintonPage
