import { useEffect, useState } from 'react'
import { getApiErrorMessage } from '../api/errors'
import { getGroups, type GroupSummary } from '../api/groups'
import { cancelBadmintonSession, confirmBadmintonSession, createBadmintonSession, getBadmintonSeasons, getBadmintonSessions, getBadmintonVenues, joinBadmintonSession, leaveBadmintonSession, openBadmintonSession, type BadmintonSeason, type BadmintonSession, type Venue } from '../api/badminton'
import { useAuth } from '../auth/AuthContext'

function BadmintonPage() {
  const { user } = useAuth(); const [groups, setGroups] = useState<GroupSummary[]>([]); const [groupId, setGroupId] = useState(0); const [seasons, setSeasons] = useState<BadmintonSeason[]>([]); const [venues, setVenues] = useState<Venue[]>([]); const [sessions, setSessions] = useState<BadmintonSession[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [title, setTitle] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [deadline, setDeadline] = useState(''); const [venueId, setVenueId] = useState(0); const [courtId, setCourtId] = useState(0); const [capacity, setCapacity] = useState('16')
  const badmintonGroups = groups.filter((g) => g.type === 'BADMINTON'); const selectedVenue = venues.find((v) => v.id === venueId)
  async function refresh() { if (!groupId) return; const [nextSessions, nextSeasons, nextVenues] = await Promise.all([getBadmintonSessions(groupId), getBadmintonSeasons(groupId), getBadmintonVenues(groupId)]); setSessions(nextSessions); setSeasons(nextSeasons); setVenues(nextVenues); if (!venueId && nextVenues[0]) setVenueId(nextVenues[0].id); if (!courtId && nextVenues[0]?.courts[0]) setCourtId(nextVenues[0].courts[0].id) }
  useEffect(() => { getGroups().then((data) => { setGroups(data); setGroupId(data.find((g) => g.type === 'BADMINTON')?.id ?? 0) }).catch((e) => setError(getApiErrorMessage(e, 'Could not load groups.'))) }, [])
  useEffect(() => { refresh().catch((e) => setError(getApiErrorMessage(e, 'Could not load badminton data.'))) }, [groupId])
  async function create(event: React.FormEvent) { event.preventDefault(); try { await createBadmintonSession(groupId, { title, start: new Date(start).toISOString(), end: new Date(end).toISOString(), registrationDeadline: new Date(deadline).toISOString(), capacity: Number(capacity) || 16, seasonId: seasons[0]?.id, venueId, courtIds: [courtId] }); setMessage('Badminton session created as draft.'); setTitle(''); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not create session.')) } }
  async function act(fn: () => Promise<BadmintonSession>, text: string) { try { await fn(); setMessage(text); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Badminton action failed.')) } }
  return <section><div className="page-heading"><div><p className="eyebrow">Badminton operations</p><h1>Play sessions</h1><p className="intro">Manage courts, capacity, waitlist and check-in-ready sessions without duplicating calendar data.</p></div><select className="group-picker" value={groupId} onChange={(e) => setGroupId(Number(e.target.value))}>{badmintonGroups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select></div>
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}{!groupId && <div className="page-panel empty-state">Create or join a BADMINTON group first.</div>}
    {groupId && <div className="content-grid"><div><div className="section-title">Sessions</div>{sessions.length === 0 && <div className="page-panel empty-state">No badminton sessions yet.</div>}{sessions.map((s) => { const mine = s.registrations.find((r) => r.userId === user?.id); return <div className="page-panel study-card" key={s.id}><div className="study-card-header"><div><span className="source-tag source-badminton">{s.status}</span><h2>{s.title}</h2><p>{new Date(s.start).toLocaleString()} – {new Date(s.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p><p>{s.venueName} · {s.courts.map((c) => c.name).join(', ')}</p></div><span className="subtle">{s.registrations.filter((r) => r.status === 'REGISTERED' || r.status === 'CHECKED_IN').length} / {s.capacity}</span></div><div className="study-actions">{s.status === 'DRAFT' && <button className="btn btn-outline-primary" onClick={() => act(() => openBadmintonSession(s.id), 'Session opened for registration.')}>Open</button>}{s.status === 'OPEN' && <button className="btn btn-primary" onClick={() => act(() => confirmBadmintonSession(s.id), 'Session confirmed and calendar will update.')}>Confirm</button>}{(s.status === 'OPEN' || s.status === 'CONFIRMED') && <>{!mine && <button className="btn btn-outline-primary" onClick={() => act(() => joinBadmintonSession(s.id), 'Registration saved; conflict is only a warning.')}>Join</button>}{mine && mine.status !== 'CANCELLED' && <button className="btn btn-outline-secondary" onClick={() => act(() => leaveBadmintonSession(s.id), 'Registration cancelled; FIFO promotion checked.')}>Leave</button>}</>}{(s.status === 'OPEN' || s.status === 'CONFIRMED') && <button className="btn btn-outline-danger" onClick={() => act(() => cancelBadmintonSession(s.id), 'Session cancelled and calendar entries removed.')}>Cancel</button>}</div><div className="participant-pills">{s.registrations.filter((r) => r.status !== 'CANCELLED').map((r) => <span key={r.id}>{r.displayName} · {r.status}{r.conflictWarning ? ' · conflict warning' : ''}</span>)}</div></div>})}</div>
      <form className="page-panel form-stack" onSubmit={create}><div><p className="eyebrow">Organizer</p><h2>Create session</h2></div><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Starts<input type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} required /></label><label>Ends<input type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} required /></label><label>Registration deadline<input type="datetime-local" value={deadline} onChange={(e) => setDeadline(e.target.value)} required /></label><label>Capacity<input type="number" min="1" value={capacity} onChange={(e) => setCapacity(e.target.value)} /></label><label>Venue<select value={venueId} onChange={(e) => setVenueId(Number(e.target.value))}>{venues.map((v) => <option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Court<select value={courtId} onChange={(e) => setCourtId(Number(e.target.value))}>{selectedVenue?.courts.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button className="btn btn-primary" disabled={!seasons[0] || !venueId || !courtId}>Create draft</button><p className="hint">Default capacity for the demo is 16. Match and ranking are intentionally not included.</p></form></div>}
  </section>
}
export default BadmintonPage
