import { useEffect, useMemo, useState } from 'react'
import { createBusyEvent, createRecurringSchedule, deleteBusyEvent, getCalendarItems, getRecurringSchedules, type CalendarItem, type WeeklySchedule } from '../api/calendar'
import { getApiErrorMessage } from '../api/errors'

const weekdays = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']
function isoDateTime(value: string) { return new Date(value).toISOString() }
function localDay(value: string) { const date = new Date(value); const pad = (part: number) => String(part).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` }
function CalendarPage() {
  const today = new Date(); const nextWeek = new Date(today.getTime() + 7 * 86400000)
  const [from, setFrom] = useState(today.toISOString().slice(0, 10)); const [to, setTo] = useState(nextWeek.toISOString().slice(0, 10))
  const [items, setItems] = useState<CalendarItem[]>([]); const [schedules, setSchedules] = useState<WeeklySchedule[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [eventTitle, setEventTitle] = useState(''); const [eventStart, setEventStart] = useState(''); const [eventEnd, setEventEnd] = useState('')
  const [scheduleTitle, setScheduleTitle] = useState(''); const [scheduleDays, setScheduleDays] = useState<string[]>(['MONDAY']); const [scheduleStart, setScheduleStart] = useState('09:00'); const [scheduleEnd, setScheduleEnd] = useState('10:00'); const [validFrom, setValidFrom] = useState(from); const [validUntil, setValidUntil] = useState(to)
  async function refresh() { setItems(await getCalendarItems(`${from}T00:00:00+07:00`, `${to}T23:59:59+07:00`)); setSchedules(await getRecurringSchedules()) }
  useEffect(() => { refresh().catch((e) => setError(getApiErrorMessage(e, 'Could not load calendar.'))) }, [from, to])
  const grouped = useMemo(() => items.reduce<Record<string, CalendarItem[]>>((result, item) => { const key = localDay(item.start); (result[key] ??= []).push(item); return result }, {}), [items])
  async function addEvent(event: React.FormEvent) { event.preventDefault(); setError(''); try { await createBusyEvent({ title: eventTitle, start: isoDateTime(eventStart), end: isoDateTime(eventEnd) }); setEventTitle(''); setMessage('Busy event added.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not add event.')) } }
  async function addSchedule(event: React.FormEvent) { event.preventDefault(); setError(''); try { await createRecurringSchedule({ title: scheduleTitle, weekdays: scheduleDays, startTime: `${scheduleStart}:00`, endTime: `${scheduleEnd}:00`, validFrom, validUntil, timezone: 'Asia/Bangkok' }); setScheduleTitle(''); setMessage('Weekly schedule added.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not add recurring schedule.')) } }
  async function removeEvent(id: number) { try { await deleteBusyEvent(id); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not delete event.')) } }
  return <section><div className="page-heading"><div><p className="eyebrow">Personal source of truth</p><h1>My calendar</h1><p className="intro">Enter a busy fact once. GroupSync expands recurring schedules and confirmed study sessions into this view.</p></div></div>
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="calendar-toolbar page-panel"><label>From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label></div>
    <div className="content-grid"><div><div className="section-title">Busy items</div>{Object.keys(grouped).length === 0 && <div className="page-panel empty-state">Nothing busy in this range.</div>}{Object.entries(grouped).map(([date, dayItems]) => <div className="calendar-day page-panel" key={date}><h2>{date}</h2>{dayItems.map((item) => <div className="calendar-item" key={`${item.sourceType}-${item.sourceId}-${item.start}`}><div><span className={`source-tag source-${item.sourceType.toLowerCase()}`}>{item.sourceType}</span><strong>{item.title}</strong><span>{new Date(item.start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} – {new Date(item.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>{item.sourceType === 'MANUAL' && <button className="btn btn-sm btn-outline-danger" onClick={() => removeEvent(item.sourceId)}>Delete</button>}</div>)}</div>)}</div>
      <div className="form-column"><form className="page-panel form-stack" onSubmit={addEvent}><div><p className="eyebrow">One-time fact</p><h2>Add busy event</h2></div><label>Title<input value={eventTitle} onChange={(e) => setEventTitle(e.target.value)} required /></label><label>Starts<input type="datetime-local" value={eventStart} onChange={(e) => setEventStart(e.target.value)} required /></label><label>Ends<input type="datetime-local" value={eventEnd} onChange={(e) => setEventEnd(e.target.value)} required /></label><button className="btn btn-primary">Add event</button></form>
      <form className="page-panel form-stack" onSubmit={addSchedule}><div><p className="eyebrow">Input once</p><h2>Weekly schedule</h2></div><label>Title<input value={scheduleTitle} onChange={(e) => setScheduleTitle(e.target.value)} placeholder="OOP class" required /></label><div><div className="form-label">Days</div><div className="weekday-grid">{weekdays.map((day) => <label className="weekday-check" key={day}><input type="checkbox" checked={scheduleDays.includes(day)} onChange={(e) => setScheduleDays(e.target.checked ? [...scheduleDays, day] : scheduleDays.filter((value) => value !== day))} />{day.slice(0, 3)}</label>)}</div></div><div className="two-fields"><label>Start<input type="time" value={scheduleStart} onChange={(e) => setScheduleStart(e.target.value)} required /></label><label>End<input type="time" value={scheduleEnd} onChange={(e) => setScheduleEnd(e.target.value)} required /></label></div><div className="two-fields"><label>Valid from<input type="date" value={validFrom} onChange={(e) => setValidFrom(e.target.value)} required /></label><label>Until<input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} required /></label></div><button className="btn btn-outline-primary">Add weekly schedule</button></form>
      <div className="page-panel"><div className="section-title">Saved recurring sources</div>{schedules.map((schedule) => <div className="saved-source" key={schedule.id}><strong>{schedule.title}</strong><span>{schedule.weekdays.map((day) => day.slice(0, 3)).join(', ')} · {schedule.startTime.slice(0, 5)}–{schedule.endTime.slice(0, 5)}</span></div>)}</div></div>
    </div></section>
}
export default CalendarPage
