import { useEffect, useMemo, useState } from 'react'
import { createBusyEvent, createRecurringSchedule, deleteBusyEvent, deleteRecurringSchedule, duplicateBusyEvent, duplicateRecurringSchedule, getBusyEvents, getCalendarItems, getRecurringSchedules, updateBusyEvent, type BusyEvent, type CalendarItem, type WeeklySchedule } from '../api/calendar'
import { getApiErrorMessage } from '../api/errors'

const weekdays = ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY']
function isoDateTime(value: string) { return new Date(value).toISOString() }
function localDay(value: string) { const date = new Date(value); const pad = (part: number) => String(part).padStart(2, '0'); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}` }
function localInput(value: string) { return new Date(value).toISOString().slice(0, 16) }

function CalendarPage() {
  const today = new Date(); const nextWeek = new Date(today.getTime() + 7 * 86400000)
  const [from, setFrom] = useState(today.toISOString().slice(0, 10)); const [to, setTo] = useState(nextWeek.toISOString().slice(0, 10))
  const [items, setItems] = useState<CalendarItem[]>([]); const [manualEvents, setManualEvents] = useState<BusyEvent[]>([]); const [schedules, setSchedules] = useState<WeeklySchedule[]>([])
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [editingEventId, setEditingEventId] = useState<number | null>(null)
  const [eventTitle, setEventTitle] = useState(''); const [eventStart, setEventStart] = useState(''); const [eventEnd, setEventEnd] = useState(''); const [eventDescription, setEventDescription] = useState(''); const [eventCategory, setEventCategory] = useState('PERSONAL'); const [eventLocation, setEventLocation] = useState(''); const [eventReminder, setEventReminder] = useState('')
  const [scheduleTitle, setScheduleTitle] = useState(''); const [scheduleDays, setScheduleDays] = useState<string[]>(['MONDAY']); const [scheduleStart, setScheduleStart] = useState('09:00'); const [scheduleEnd, setScheduleEnd] = useState('10:00'); const [validFrom, setValidFrom] = useState(from); const [validUntil, setValidUntil] = useState(to); const [frequency, setFrequency] = useState('WEEKLY')

  async function refresh() { const [nextItems, nextManual, nextSchedules] = await Promise.all([getCalendarItems(`${from}T00:00:00+07:00`, `${to}T23:59:59+07:00`), getBusyEvents(), getRecurringSchedules()]); setItems(nextItems); setManualEvents(nextManual); setSchedules(nextSchedules) }
  useEffect(() => { refresh().catch((e) => setError(getApiErrorMessage(e, 'Could not load calendar.'))) }, [from, to])
  const grouped = useMemo(() => items.reduce<Record<string, CalendarItem[]>>((result, item) => { const key = localDay(item.start); (result[key] ??= []).push(item); return result }, {}), [items])
  function clearEventForm() { setEditingEventId(null); setEventTitle(''); setEventStart(''); setEventEnd(''); setEventDescription(''); setEventCategory('PERSONAL'); setEventLocation(''); setEventReminder('') }
  function editEvent(event: BusyEvent) { setEditingEventId(event.id); setEventTitle(event.title); setEventStart(localInput(event.start)); setEventEnd(localInput(event.end)); setEventDescription(event.description ?? ''); setEventCategory(event.category ?? 'PERSONAL'); setEventLocation(event.location ?? ''); setEventReminder(event.reminderMinutes?.toString() ?? '') }
  async function saveEvent(event: React.FormEvent) { event.preventDefault(); setError(''); const payload = { title: eventTitle, start: isoDateTime(eventStart), end: isoDateTime(eventEnd), description: eventDescription || undefined, category: eventCategory || undefined, location: eventLocation || undefined, visibility: 'PRIVATE', reminderMinutes: eventReminder ? Number(eventReminder) : undefined }; try { if (editingEventId) await updateBusyEvent(editingEventId, payload); else await createBusyEvent(payload); clearEventForm(); setMessage(editingEventId ? 'Busy event updated.' : 'Busy event added.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not save event.')) } }
  async function addSchedule(event: React.FormEvent) { event.preventDefault(); setError(''); try { await createRecurringSchedule({ title: scheduleTitle, weekdays: frequency === 'DAILY' ? weekdays : scheduleDays, startTime: `${scheduleStart}:00`, endTime: `${scheduleEnd}:00`, validFrom, validUntil, timezone: 'Asia/Bangkok', description: undefined, category: 'RECURRING', location: undefined, visibility: 'PRIVATE', reminderMinutes: undefined, frequency }); setScheduleTitle(''); setMessage('Recurring schedule added.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not add recurring schedule.')) } }
  async function removeEvent(id: number) { try { await deleteBusyEvent(id); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not delete event.')) } }
  async function duplicateEvent(id: number) { try { await duplicateBusyEvent(id); setMessage('Event duplicated.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not duplicate event.')) } }
  async function duplicateSchedule(id: number) { try { await duplicateRecurringSchedule(id); setMessage('Recurring schedule duplicated.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not duplicate schedule.')) } }
  async function removeSchedule(id: number) { try { await deleteRecurringSchedule(id); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not delete schedule.')) } }

  return <section><div className="page-heading"><div><p className="eyebrow">Personal source of truth</p><h1>My calendar</h1><p className="intro">Enter a busy fact once. GroupSync stores it in PostgreSQL and derives recurring, Study and Badminton items into this view.</p></div></div>
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    <div className="calendar-toolbar page-panel"><label>From<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label>To<input type="date" value={to} onChange={(e) => setTo(e.target.value)} /></label></div>
    <div className="content-grid"><div><div className="section-title">Busy items</div>{Object.keys(grouped).length === 0 && <div className="page-panel empty-state">Nothing busy in this range.</div>}{Object.entries(grouped).map(([date, dayItems]) => <div className="calendar-day page-panel" key={date}><h2>{date}</h2>{dayItems.map((item) => <div className="calendar-item" key={`${item.sourceType}-${item.sourceId}-${item.start}`}><div><span className={`source-tag source-${item.sourceType.toLowerCase()}`}>{item.sourceType}</span><strong>{item.title}</strong><span>{new Date(item.start).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} – {new Date(item.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>{item.sourceType === 'MANUAL' && <button className="btn btn-sm btn-outline-danger" onClick={() => removeEvent(item.sourceId)}>Delete</button>}</div>)}</div>)}</div>
      <div className="form-column"><form className="page-panel form-stack" onSubmit={saveEvent}><div><p className="eyebrow">One-time fact</p><h2>{editingEventId ? 'Edit busy event' : 'Add busy event'}</h2></div><label>Title<input value={eventTitle} onChange={(e) => setEventTitle(e.target.value)} required /></label><label>Description<textarea value={eventDescription} onChange={(e) => setEventDescription(e.target.value)} rows={2} /></label><label>Category<input value={eventCategory} onChange={(e) => setEventCategory(e.target.value)} /></label><label>Location<input value={eventLocation} onChange={(e) => setEventLocation(e.target.value)} /></label><label>Starts<input type="datetime-local" value={eventStart} onChange={(e) => setEventStart(e.target.value)} required /></label><label>Ends<input type="datetime-local" value={eventEnd} onChange={(e) => setEventEnd(e.target.value)} required /></label><label>Reminder minutes before<input type="number" min="0" value={eventReminder} onChange={(e) => setEventReminder(e.target.value)} placeholder="Optional" /></label><div className="study-actions"><button className="btn btn-primary">{editingEventId ? 'Save changes' : 'Add event'}</button>{editingEventId && <button type="button" className="btn btn-outline-secondary" onClick={clearEventForm}>Cancel</button>}</div></form>
      <div className="page-panel"><div className="section-title">Saved one-time events</div>{manualEvents.length === 0 && <p className="hint">No manual events yet.</p>}{manualEvents.map((event) => <div className="saved-source" key={event.id}><strong>{event.title}</strong><span>{new Date(event.start).toLocaleString()} · {event.category || 'PERSONAL'}</span><div className="study-actions"><button className="mini-button" onClick={() => editEvent(event)}>Edit</button><button className="mini-button" onClick={() => duplicateEvent(event.id)}>Duplicate</button><button className="mini-button" onClick={() => removeEvent(event.id)}>Delete</button></div></div>)}</div>
      <form className="page-panel form-stack" onSubmit={addSchedule}><div><p className="eyebrow">Input once</p><h2>Recurring schedule</h2></div><label>Title<input value={scheduleTitle} onChange={(e) => setScheduleTitle(e.target.value)} placeholder="OOP class" required /></label><label>Frequency<select value={frequency} onChange={(e) => setFrequency(e.target.value)}><option value="WEEKLY">Every selected weekday</option><option value="DAILY">Every day</option></select></label><div><div className="form-label">Days</div><div className="weekday-grid">{weekdays.map((day) => <label className="weekday-check" key={day}><input type="checkbox" checked={frequency === 'DAILY' || scheduleDays.includes(day)} disabled={frequency === 'DAILY'} onChange={(e) => setScheduleDays(e.target.checked ? [...scheduleDays, day] : scheduleDays.filter((value) => value !== day))} />{day.slice(0, 3)}</label>)}</div></div><div className="two-fields"><label>Start<input type="time" value={scheduleStart} onChange={(e) => setScheduleStart(e.target.value)} required /></label><label>End<input type="time" value={scheduleEnd} onChange={(e) => setScheduleEnd(e.target.value)} required /></label></div><div className="two-fields"><label>Valid from<input type="date" value={validFrom} onChange={(e) => setValidFrom(e.target.value)} required /></label><label>Until<input type="date" value={validUntil} onChange={(e) => setValidUntil(e.target.value)} required /></label></div><button className="btn btn-outline-primary">Add recurring schedule</button></form>
      <div className="page-panel"><div className="section-title">Saved recurring sources</div>{schedules.map((schedule) => <div className="saved-source" key={schedule.id}><strong>{schedule.title}</strong><span>{schedule.frequency === 'DAILY' ? 'Every day' : schedule.weekdays.map((day) => day.slice(0, 3)).join(', ')} · {schedule.startTime.slice(0, 5)}–{schedule.endTime.slice(0, 5)}</span><div className="study-actions"><button className="mini-button" onClick={() => duplicateSchedule(schedule.id)}>Duplicate</button><button className="mini-button" onClick={() => removeSchedule(schedule.id)}>Delete</button></div></div>)}</div></div>
    </div></section>
}
export default CalendarPage
