import { FileText, Plus, Search } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { createNote, getResources, type Resource } from '../api/knowledge'

export default function KnowledgeLibraryPage() {
  const [resources, setResources] = useState<Resource[]>([]); const [query, setQuery] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const load = (value = '') => getResources(value).then(setResources).catch(() => setError('Your library could not be loaded.'))
  useEffect(() => { load() }, [])
  async function saveNote(e: React.FormEvent) { e.preventDefault(); try { await createNote(title, content); setTitle(''); setContent(''); setOpen(false); load(query) } catch { setError('The note could not be saved.') } }
  return <section className="kos-page kos-library"><header className="kos-page-header"><div><p className="kos-kicker">YOUR LIBRARY</p><h1>Keep the good stuff close.</h1></div><button className="kos-button kos-button--primary" onClick={() => setOpen(true)}><Plus size={17}/> New note</button></header><div className="kos-library-toolbar"><label><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && load(query)} placeholder="Search titles" /></label><span>{resources.length} resources</span></div>{error && <p className="kos-error">{error}</p>}{resources.length ? <div className="kos-resource-grid">{resources.map((resource, index) => <Link className="kos-resource" to={`/library/${resource.id}`} key={resource.id}><div className={`kos-resource-cover kos-resource-cover--${index % 4}`}><FileText size={26}/></div><p>{resource.resourceType}</p><h2>{resource.title}</h2><small>{resource.processingStatus === 'READY' ? 'Ready to ask' : resource.processingStatus.toLowerCase()}</small></Link>)}</div> : <div className="kos-empty"><FileText size={28}/><h2>Nothing here yet.</h2><p>Save a note first, then import the resources you want to question later.</p></div>}{open && <div className="kos-modal" role="dialog" aria-modal="true"><form onSubmit={saveNote}><button className="kos-modal-close" type="button" onClick={() => setOpen(false)}>Close</button><p className="kos-kicker">NEW NOTE</p><label>Title<input value={title} onChange={e => setTitle(e.target.value)} required /></label><label>Thoughts<textarea value={content} onChange={e => setContent(e.target.value)} required /></label><button className="kos-button kos-button--primary">Save note</button></form></div>}</section>
}
