import { BrainCircuit, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { askKnowledge, getResources, type AskResponse, type Resource } from '../api/knowledge'

type Scope = 'THIS_RESOURCE' | 'SELECTED_RESOURCES' | 'COLLECTION' | 'LIBRARY'
export default function KnowledgeAskPage() {
  const [resources, setResources] = useState<Resource[]>([]); const [scope, setScope] = useState<Scope>('LIBRARY'); const [selected, setSelected] = useState<number[]>([]); const [question, setQuestion] = useState(''); const [result, setResult] = useState<AskResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('')
  useEffect(() => { getResources().then(setResources).catch(() => setError('Your resources could not be loaded.')) }, [])
  const toggle = (id: number) => setSelected(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id])
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(''); if ((scope === 'THIS_RESOURCE' && selected.length !== 1) || (scope === 'SELECTED_RESOURCES' && selected.length === 0)) { setError('Choose the resources you want KnowledgeOS to use.'); return } setLoading(true); try { setResult(await askKnowledge({ question, scope, resourceId: scope === 'THIS_RESOURCE' ? selected[0] : undefined, resourceIds: scope === 'SELECTED_RESOURCES' ? selected : undefined })) } catch { setError('KnowledgeOS could not answer right now.') } finally { setLoading(false) } }
  return <section className="kos-page kos-ask"><p className="kos-kicker">ASK KNOWLEDGEOS</p><h1>Ask what your sources can answer.</h1><div className="kos-ask-layout"><form className="kos-ask-stage" onSubmit={submit}><BrainCircuit size={30}/><label>Scope<select value={scope} onChange={event => { setScope(event.target.value as Scope); setSelected([]) }}><option value="LIBRARY">Entire library</option><option value="THIS_RESOURCE">One resource</option><option value="SELECTED_RESOURCES">Selected resources</option><option value="COLLECTION" disabled>Collection (coming with collection setup)</option></select></label>{(scope === 'THIS_RESOURCE' || scope === 'SELECTED_RESOURCES') && <div className="kos-resource-picker">{resources.map(resource => <label key={resource.id}><input type={scope === 'THIS_RESOURCE' ? 'radio' : 'checkbox'} checked={selected.includes(resource.id)} onChange={() => scope === 'THIS_RESOURCE' ? setSelected([resource.id]) : toggle(resource.id)} />{resource.title}</label>)}</div>}<label>Your question<textarea value={question} onChange={event => setQuestion(event.target.value)} placeholder="What would you like to understand?" required /></label>{error && <p className="kos-error">{error}</p>}<button className="kos-button kos-button--primary" disabled={loading}>{loading ? 'Finding evidence...' : <>Ask library <Send size={16}/></>}</button></form>{result && <article className="kos-answer"><p className="kos-kicker">{result.grounded ? 'GROUNDED ANSWER' : 'INSUFFICIENT CONTEXT'}</p><p>{result.answer}</p>{result.citations.length > 0 && <div><h2>Evidence</h2>{result.citations.map(citation => <details key={citation.chunkId}><summary>[{citation.citationOrder}] {citation.resourceTitle}</summary><p>{citation.evidenceExcerpt}</p></details>)}</div>}</article>}</div></section>
}
