import { FileText, FolderPlus, Plus, Search, Upload } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { assignResourceToCollection, createCollection, createNote, getCollections, getResources, uploadResource, type KnowledgeCollection, type Resource } from '../api/knowledge'

export default function KnowledgeLibraryPage() {
  const [resources, setResources] = useState<Resource[]>([]); const [collections,setCollections]=useState<KnowledgeCollection[]>([]); const [query, setQuery] = useState(''); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [open, setOpen] = useState(false); const [collectionOpen,setCollectionOpen]=useState(false); const [collectionName,setCollectionName]=useState(''); const [error, setError] = useState(''); const [busy,setBusy]=useState(false)
  const load = (value = '') => getResources(value).then(setResources).catch(() => setError('Your library could not be loaded.'))
  useEffect(() => { load(); getCollections().then(setCollections).catch(()=>setError('Collections could not be loaded.')) }, [])
  async function saveNote(e: React.FormEvent) { e.preventDefault(); setError(''); try { await createNote(title, content); setTitle(''); setContent(''); setOpen(false); load(query) } catch { setError('The note could not be saved.') } }
  async function importFile(file?:File){if(!file)return;setBusy(true);setError('');try{await uploadResource(file);await load(query)}catch{setError('The resource could not be imported.')}finally{setBusy(false)}}
  async function saveCollection(e:React.FormEvent){e.preventDefault();try{const created=await createCollection(collectionName);setCollections(values=>[created,...values]);setCollectionName('');setCollectionOpen(false)}catch{setError('The collection could not be created.')}}
  async function assign(collectionId:number,resourceId:number){try{await assignResourceToCollection(collectionId,resourceId)}catch{setError('The resource could not be added to that collection.')}}
  return <section className="kos-page kos-library"><header className="kos-page-header"><div><p className="kos-kicker">YOUR LIBRARY</p><h1>Keep the good stuff close.</h1></div><div className="kos-library-actions"><label className="kos-button"><Upload size={17}/>{busy?'Importing...':'Import file'}<input type="file" accept=".pdf,.docx,.txt,.md,.markdown" hidden disabled={busy} onChange={e=>importFile(e.target.files?.[0])}/></label><button className="kos-button" onClick={()=>setCollectionOpen(true)}><FolderPlus size={17}/> Collection</button><button className="kos-button kos-button--primary" onClick={() => setOpen(true)}><Plus size={17}/> New note</button></div></header><div className="kos-library-toolbar"><label><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && load(query)} placeholder="Search titles" /></label><span>{resources.length} resources · {collections.length} collections</span></div>{error && <p className="kos-error">{error}</p>}{resources.length ? <div className="kos-resource-grid">{resources.map((resource, index) => <article className="kos-resource" key={resource.id}><Link to={`/library/${resource.id}`}><div className={`kos-resource-cover kos-resource-cover--${index % 4}`}><FileText size={26}/></div><p>{resource.resourceType}</p><h2>{resource.title}</h2><small>{resource.processingStatus === 'READY' ? 'Ready to ask' : resource.processingStatus.toLowerCase()}</small></Link>{collections.length>0&&<label className="kos-collection-select">Add to collection<select defaultValue="" onChange={e=>{if(e.target.value)assign(Number(e.target.value),resource.id)}}><option value="">Choose…</option>{collections.map(collection=><option key={collection.id} value={collection.id}>{collection.name}</option>)}</select></label>}</article>)}</div> : <div className="kos-empty"><FileText size={28}/><h2>Nothing here yet.</h2><p>Save a note first, then import the resources you want to question later.</p></div>}{open && <div className="kos-modal" role="dialog" aria-modal="true"><form onSubmit={saveNote}><button className="kos-modal-close" type="button" onClick={() => setOpen(false)}>Close</button><p className="kos-kicker">NEW NOTE</p><label>Title<input value={title} onChange={e => setTitle(e.target.value)} required /></label><label>Thoughts<textarea value={content} onChange={e => setContent(e.target.value)} required /></label><button className="kos-button kos-button--primary">Save note</button></form></div>}{collectionOpen&&<div className="kos-modal" role="dialog" aria-modal="true"><form onSubmit={saveCollection}><button className="kos-modal-close" type="button" onClick={()=>setCollectionOpen(false)}>Close</button><p className="kos-kicker">NEW COLLECTION</p><label>Name<input value={collectionName} onChange={e=>setCollectionName(e.target.value)} required/></label><button className="kos-button kos-button--primary">Create collection</button></form></div>}</section>
}
