import { ArrowLeft, BrainCircuit, FileText, Trash2 } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useEffect, useState } from 'react'
import { createResourceNote, deleteResourceNote, getRelatedResources, getResource, getResourceActivity, getResourceContent, getResourceNotes, updateResourceNote, updateResourceProgress, type Resource, type ResourceActivity, type ResourceNote } from '../api/knowledge'

export default function ResourceWorkspacePage() {
  const resourceId=Number(useParams().resourceId); const [resource,setResource]=useState<Resource|null>(null),[content,setContent]=useState(''),[tab,setTab]=useState('Overview'),[notes,setNotes]=useState<ResourceNote[]>([]),[related,setRelated]=useState<Resource[]>([]),[activity,setActivity]=useState<ResourceActivity|null>(null),[draft,setDraft]=useState(''),[error,setError]=useState('')
  const load=()=>Promise.all([getResource(resourceId),getResourceContent(resourceId),getResourceNotes(resourceId),getRelatedResources(resourceId),getResourceActivity(resourceId)]).then(([item,text,n,r,a])=>{setResource(item);setContent(text);setNotes(n);setRelated(r);setActivity(a)}).catch(()=>setError('This resource could not be loaded.'))
  useEffect(()=>{load()},[resourceId])
  async function addNote(){if(!draft.trim())return; try{await createResourceNote(resourceId,draft);setDraft('');setNotes(await getResourceNotes(resourceId))}catch{setError('The note could not be saved.')}}
  async function removeNote(id:number){try{await deleteResourceNote(resourceId,id);setNotes(await getResourceNotes(resourceId))}catch{setError('The note could not be deleted.')}}
  async function saveNote(id:number,content:string){try{await updateResourceNote(resourceId,id,content);setNotes(await getResourceNotes(resourceId))}catch{setError('The note could not be updated.')}}
  async function progress(value:number){try{setActivity(await updateResourceProgress(resourceId,value))}catch{setError('Progress could not be saved.')}}
  if(error&&!resource)return <section className="kos-page"><p className="kos-error">{error}</p></section>
  if(!resource)return <section className="kos-page"><div className="kos-empty">Loading resource...</div></section>
  return <section className="kos-page kos-workspace"><Link className="kos-back" to="/library"><ArrowLeft size={16}/> Library</Link><header><div><p className="kos-kicker">{resource.resourceType}</p><h1>{resource.title}</h1><p>{resource.description||'A resource in your KnowledgeOS library.'}</p></div><Link className="kos-button kos-button--primary" to={`/ask?resource=${resource.id}`}><BrainCircuit size={17}/> Ask this resource</Link></header><nav className="kos-tabs">{['Overview','Reader','Notes','Related','Activity'].map(item=><button key={item} className={tab===item?'is-active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>{error&&<p className="kos-error">{error}</p>}{tab==='Overview'&&<div className="kos-workspace-overview"><FileText size={32}/><h2>Ready for retrieval</h2><p>Processing status: {resource.processingStatus}. Use Ask this resource to keep answers constrained to this source.</p></div>}{tab==='Reader'&&<article className="kos-reader">{content}</article>}{tab==='Notes'&&<div className="kos-notes"><label>Add a note<textarea value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Capture an idea or question..."/></label><button className="kos-button kos-button--primary" onClick={addNote}>Save note</button>{notes.length?notes.map(note=><article key={note.id}><textarea defaultValue={note.content} onBlur={event=>saveNote(note.id,event.target.value)}/><button aria-label="Delete note" onClick={()=>removeNote(note.id)}><Trash2 size={15}/></button></article>):<p className="kos-empty">No notes yet.</p>}</div>}{tab==='Related'&&<div className="kos-related">{related.length?related.map(item=><Link key={item.id} to={`/library/${item.id}`}><p className="kos-kicker">{item.resourceType}</p><h2>{item.title}</h2><p>{item.description}</p></Link>):<div className="kos-empty"><h2>No related resources yet.</h2><p>Related resources appear when explicit relationships are saved.</p></div>}</div>}{tab==='Activity'&&<div className="kos-activity"><h2>Learning progress</h2><p>{activity?.progress_percent??0}% complete · {activity?.note_count??0} notes</p><input aria-label="Reading progress" type="range" min="0" max="100" value={activity?.progress_percent??0} onChange={event=>progress(Number(event.target.value))}/><p>Processing: {activity?.processing_status}</p><p>Last updated: {activity?.updated_at?new Date(activity.updated_at).toLocaleString():'Not yet recorded'}</p></div>}</section>
}
