import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { getApiErrorMessage } from '../api/errors'
import { getGroups, type GroupSummary } from '../api/groups'
import { searchAvailability, type AvailabilityCandidate } from '../api/availability'
import { cancelStudySession, confirmStudySession, createStudySession, getStudySessions, joinStudySession, type StudySession } from '../api/study'
import { useAuth } from '../auth/AuthContext'

function StudyPage() {
  const { user } = useAuth(); const [params] = useSearchParams(); const [groups, setGroups] = useState<GroupSummary[]>([]); const [groupId, setGroupId] = useState(Number(params.get('groupId') ?? 0)); const [sessions, setSessions] = useState<StudySession[]>([]); const [candidates, setCandidates] = useState<AvailabilityCandidate[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  const [topic, setTopic] = useState(''); const [goal, setGoal] = useState(''); const [location, setLocation] = useState(''); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [capacity, setCapacity] = useState('')
  const [searchFrom, setSearchFrom] = useState(''); const [searchTo, setSearchTo] = useState(''); const [duration, setDuration] = useState('60');
  const studyGroups = groups.filter((group) => group.type === 'STUDY')
  async function refreshSessions() { if (groupId) setSessions(await getStudySessions(groupId)) }
  useEffect(() => { getGroups().then((data) => { setGroups(data); if (!groupId) setGroupId(data.find((group) => group.type === 'STUDY')?.id ?? 0) }).catch((e) => setError(getApiErrorMessage(e, 'Could not load groups.'))) }, [])
  useEffect(() => { refreshSessions().catch((e) => setError(getApiErrorMessage(e, 'Could not load study sessions.'))) }, [groupId])
  async function create(event: React.FormEvent) { event.preventDefault(); try { await createStudySession(groupId, { topic, goal, location, start: new Date(start).toISOString(), end: new Date(end).toISOString(), capacity: capacity ? Number(capacity) : null }); setMessage('Study session created.'); setTopic(''); await refreshSessions() } catch (e) { setError(getApiErrorMessage(e, 'Could not create study session.')) } }
  async function action(fn: () => Promise<StudySession>, success: string) { try { await fn(); setMessage(success); await refreshSessions() } catch (e) { setError(getApiErrorMessage(e, 'Study action failed.')) } }
  async function findAvailability(event: React.FormEvent) { event.preventDefault(); try { setCandidates(await searchAvailability(groupId, { from: new Date(searchFrom).toISOString(), to: new Date(searchTo).toISOString(), durationMinutes: Number(duration), requiredMemberIds: [], minimumAttendance: 1, strategy: 'MAXIMUM' })); setMessage('Availability suggestions updated.') } catch (e) { setError(getApiErrorMessage(e, 'Could not search availability.')) } }
  return <section><div className="page-heading"><div><p className="eyebrow">Study vertical</p><h1>Study sessions</h1><p className="intro">Find a slot, create a session, and let confirmed participation appear on the calendar automatically.</p></div><select className="group-picker" value={groupId} onChange={(e) => setGroupId(Number(e.target.value))}>{studyGroups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div>
    {error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}
    {!groupId && <div className="page-panel empty-state">Create or join a STUDY group first.</div>}
    {groupId && <div className="content-grid"><div><div className="section-title">Sessions</div>{sessions.length === 0 && <div className="page-panel empty-state">No study sessions yet.</div>}{sessions.map((session) => { const joined = session.participants.some((participant) => participant.userId === user?.id); const organizer = session.participants[0]?.userId === user?.id; return <div className="page-panel study-card" key={session.id}><div className="study-card-header"><div><span className="source-tag source-study">{session.status}</span><h2>{session.topic}</h2><p>{new Date(session.start).toLocaleString()} – {new Date(session.end).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div><span className="subtle">{session.participants.length}{session.capacity ? ` / ${session.capacity}` : ''} joined</span></div><p>{session.goal || 'No goal added.'}{session.location ? ` · ${session.location}` : ''}</p><div className="study-actions">{session.status === 'OPEN' && !joined && <button className="btn btn-outline-primary" onClick={() => action(() => joinStudySession(session.id), 'Joined study session.')}>Join</button>}{session.status === 'OPEN' && organizer && <button className="btn btn-primary" onClick={() => action(() => confirmStudySession(session.id), 'Session confirmed; participants are now busy.')}>Confirm</button>}{(session.status === 'OPEN' || session.status === 'CONFIRMED') && organizer && <button className="btn btn-outline-danger" onClick={() => action(() => cancelStudySession(session.id), 'Session cancelled; derived calendar item removed.')}>Cancel</button>}</div><div className="participant-pills">{session.participants.map((participant) => <span key={participant.userId}>{participant.displayName} · {participant.attendance}</span>)}</div></div>})}</div>
      <div className="form-column"><form className="page-panel form-stack" onSubmit={findAvailability}><div><p className="eyebrow">Suggest a slot</p><h2>Availability search</h2></div><label>From<input type="datetime-local" value={searchFrom} onChange={(e) => setSearchFrom(e.target.value)} required /></label><label>To<input type="datetime-local" value={searchTo} onChange={(e) => setSearchTo(e.target.value)} required /></label><label>Duration<select value={duration} onChange={(e) => setDuration(e.target.value)}><option value="30">30 minutes</option><option value="60">1 hour</option><option value="90">90 minutes</option><option value="120">2 hours</option></select></label><button className="btn btn-outline-primary">Find candidate slots</button>{candidates.slice(0, 6).map((candidate) => <button type="button" className="candidate-slot" key={candidate.start} onClick={() => { setStart(candidate.start.slice(0, 16)); setEnd(candidate.end.slice(0, 16)) }}>{new Date(candidate.start).toLocaleString()} · {candidate.attendance} available</button>)}</form>
      <form className="page-panel form-stack" onSubmit={create}><div><p className="eyebrow">Manual or suggested</p><h2>Create session</h2></div><label>Topic<input value={topic} onChange={(e) => setTopic(e.target.value)} required /></label><label>Goal<textarea value={goal} onChange={(e) => setGoal(e.target.value)} rows={2} /></label><label>Location / link<input value={location} onChange={(e) => setLocation(e.target.value)} /></label><label>Starts<input type="datetime-local" value={start} onChange={(e) => setStart(e.target.value)} required /></label><label>Ends<input type="datetime-local" value={end} onChange={(e) => setEnd(e.target.value)} required /></label><label>Capacity<input type="number" min="1" value={capacity} onChange={(e) => setCapacity(e.target.value)} placeholder="Optional" /></label><button className="btn btn-primary">Create study session</button></form></div>
    </div>}</section>
}
export default StudyPage
