import { useEffect, useState } from 'react'
import { getGroups, type GroupSummary } from '../api/groups'
import { getBadmintonSeasons, getBadmintonSessions, type BadmintonSeason, type BadmintonSession } from '../api/badminton'
import { completeTournament, createTournament, getTournamentBracket, getTournamentParticipants, getTournaments, openTournament, registerTournamentParticipant, startTournament, type Bracket, type Tournament, type TournamentParticipant } from '../api/tournaments'
import { getApiErrorMessage } from '../api/errors'
function TournamentPage() {
  const [groups, setGroups] = useState<GroupSummary[]>([]); const [groupId, setGroupId] = useState(0); const [seasons, setSeasons] = useState<BadmintonSeason[]>([]); const [sessions, setSessions] = useState<BadmintonSession[]>([]); const [tournaments, setTournaments] = useState<Tournament[]>([]); const [participants, setParticipants] = useState<TournamentParticipant[]>([]); const [bracket, setBracket] = useState<Bracket[]>([]); const [name, setName] = useState(''); const [participantId, setParticipantId] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('')
  async function refresh() { if (!groupId) return; const [s, v, t] = await Promise.all([getBadmintonSeasons(groupId), getBadmintonSessions(groupId), getTournaments(groupId)]); setSeasons(s); setSessions(v); setTournaments(t); if (t[0]) { setParticipants(await getTournamentParticipants(t[0].id)); setBracket(await getTournamentBracket(t[0].id)) } }
  useEffect(() => { getGroups().then((items) => { const badminton = items.filter((g) => g.type === 'BADMINTON'); setGroups(badminton); setGroupId(badminton[0]?.id ?? 0) }).catch((e) => setError(getApiErrorMessage(e, 'Could not load groups.'))) }, [])
  useEffect(() => { refresh().catch((e) => setError(getApiErrorMessage(e, 'Could not load tournaments.'))) }, [groupId])
  async function create() { try { const session = sessions.find((s) => s.status === 'CONFIRMED' || s.status === 'PLAYING'); if (!seasons[0] || !session) throw new Error('Need an active season and confirmed/playing badminton session.'); await createTournament(groupId, { name, seasonId: seasons[0].id, sessionId: session.id, format: 'KNOCKOUT', maxParticipants: 16 }); setName(''); setMessage('Tournament created.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not create tournament.')) } }
  async function action(fn: () => Promise<Tournament>, text: string) { try { await fn(); setMessage(text); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Tournament action failed.')) } }
  async function register(tournamentId: number) { const id = Number(participantId); if (!id) return; try { await registerTournamentParticipant(tournamentId, id); setParticipantId(''); setMessage('Participant registered.'); await refresh() } catch (e) { setError(getApiErrorMessage(e, 'Could not register participant.')) } }
  async function complete(tournamentId: number) { const id = Number(participantId); if (!id) return; await action(() => completeTournament(tournamentId, id), 'Tournament completed.') }
  return <section><div className="page-heading"><div><p className="eyebrow">Tournament</p><h1>Badminton tournament</h1><p className="intro">A small knockout workflow reusing existing badminton sessions, participants and matches.</p></div>{groups.length > 0 && <select className="group-picker" value={groupId} onChange={(e) => setGroupId(Number(e.target.value))}>{groups.map((g) => <option key={g.id} value={g.id}>{g.name}</option>)}</select>}</div>{error && <div className="alert alert-danger">{error}</div>}{message && <div className="alert alert-success">{message}</div>}<div className="content-grid"><form className="page-panel form-stack" onSubmit={(e) => { e.preventDefault(); create() }}><h2>Create tournament</h2><label>Name<input value={name} onChange={(e) => setName(e.target.value)} required /></label><button className="btn btn-primary">Create knockout</button><p className="hint">Uses the first active Season and confirmed/playing session.</p></form><div>{tournaments.map((t) => <div className="page-panel study-card" key={t.id}><div className="study-card-header"><h2>{t.name}</h2><span>{t.status}</span></div><p>{t.format} · {t.participants}/{t.maxParticipants} participants</p><div className="study-actions">{t.status === 'DRAFT' && <button className="btn btn-outline-primary" onClick={() => action(() => openTournament(t.id), 'Registration opened.')}>Open registration</button>}{t.status === 'REGISTRATION_OPEN' && <button className="btn btn-primary" onClick={() => action(() => startTournament(t.id), 'Tournament started.')}>Start</button>}</div>{t.id === tournaments[0]?.id && <><p className="hint">Participants: {participants.map((p) => p.displayName).join(', ') || 'none'}</p>{t.status === 'REGISTRATION_OPEN' && <div className="inline-form"><input aria-label="Participant user id" placeholder="Member user id" value={participantId} onChange={(e) => setParticipantId(e.target.value)} /><button className="btn btn-outline-primary" onClick={() => register(t.id)}>Add participant</button></div>}{t.status === 'IN_PROGRESS' && <div className="inline-form"><input aria-label="Champion user id" placeholder="Champion user id" value={participantId} onChange={(e) => setParticipantId(e.target.value)} /><button className="btn btn-outline-success" onClick={() => complete(t.id)}>Complete tournament</button></div>}<div className="saved-source"><strong>Bracket</strong><span>{bracket.map((b) => `${b.stage} #${b.matchNumber} · ${b.status}${b.winnerId ? ` · winner ${b.winnerId}` : ''}`).join(' | ') || 'Matches will appear after tournament match creation.'}</span></div></>}</div>)}</div></div></section>
}
export default TournamentPage
